### ISSUE TITLE
Can two users edit case parallelly

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#100]
Is it possible that two users can edit case parallely?
For example:
User1: analyzed case "x" do some things.
User2: on the same time he analyzed case "x"

which state will  be saved?

**Comment by idanbarak** [comment]
As we discussed with omer, at the moment they cant. for now were going to refer to the case as a static entity. 
Regarding your specific question (which state will be saved?) - both of them, but only the last save would be avaliable to the users
