### ISSUE TITLE
As a <User>, I want to <Add Basic Disatnce Tool> so that <User will be able to claculate aerial distance between places>

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1011]
- [ ] Get definitions from carmel
- [ ] Add to tools toolbar
- [ ] Create visualizer

**Comment by asafMasa** [comment]
take the functionality from here
https://github.com/AnSyn/ansyn/issues/351

**Comment by carmelorr** [comment]
@asafMasa few things:
1. The measurments should indicate the distance in meters until 1 km (999.99m).
2. The numbers should be apart ? see image- 
![image](https://user-images.githubusercontent.com/26301386/34489416-f26e9aaa-efe4-11e7-8e1c-5f34871bb2c9.png)
3. Can you please move the text to the middle of the line? it is not clear..see image
![image](https://user-images.githubusercontent.com/26301386/34489494-3acff3f2-efe5-11e7-8a8f-0d1feef1e4db.png)
4.The distance is wrong. how can they all be the same?
![image](https://user-images.githubusercontent.com/26301386/34489537-680f7f0e-efe5-11e7-8e96-1b58b4a4c7e9.png)
![image](https://user-images.githubusercontent.com/26301386/34489698-01c96722-efe6-11e7-8063-247e4472aab8.png)

**Comment by asafMasa** [comment]
@carmelorr i've fixed it please test it again
