### ISSUE TITLE
Manual image enhancement - Reset all

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1019]

**Comment by carmelorr** [comment]
Please see-
![image](https://user-images.githubusercontent.com/26301386/34487333-92b4bcfa-efdc-11e7-9002-085351a5cf43.png)

the users will be able to reset all parameters by pressing the "reset all" button.
in addition, they will be able to reset each parameter by hovering and pressing "reset" (similar to the filters menu functionality)

**Comment by carmelorr** [comment]
@asafMasa please see as mentioned above- in addition, they will be able to reset each parameter by hovering and pressing "reset" (similar to the filters menu functionality)

**Comment by carmelorr** [comment]
@shaharido1 is it up supposed to be up now? i don't see it

**Comment by shaharido1** [comment]
it's on ansyn.io:81...

**Comment by carmelorr** [comment]
@shaharido1 the hover still does not work. i am moving this to icebox since it is in medium priority.
