### ISSUE TITLE
Not geo registered map hide heatmap/polygons.

### ISSUE THREAD

**Issue by yairtawil** [AnSyn/ansyn#1024]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior** 

 - Click on display overlays tool (heatmap/polygons) 
 - Double click on overlay that not geo registered.
 - Double click on overlay that geo registered.
 
result: 
- polylines/heatman not being displayed.
- 'display overlay' button is on.
 
**Expected behavior** 

polylines/heatman should being displayed.

**Comment by carmelorr** [comment]
Please see bug #1072
