### ISSUE TITLE
filters - resolution slider - change infinity/-infinity indications

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1025]
change "-infinity" to "Min"

change "infinity" to "Max"

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/34488930-07fedb84-efe3-11e7-9f5b-46622b29ecd2.png)

![image](https://user-images.githubusercontent.com/26301386/34489006-5af25e2e-efe3-11e7-8045-150075c02ebc.png)
