### ISSUE TITLE
Bug- presented overlays do not appear after sharing case 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1034]
**Current behavior** 
after sharing a case  (share case not share link) with 2 presented overlays- only one of them appear after pasting the link in a new tab. 

**Expected behavior** 
all presented overlays should appear 

**Minimal reproduction of the problem with instructions** 
open new case
open more then one overlay
share case

**Comment by asafMasa** [comment]
@idanbarak @carmelorr since it happend outside i will lower its priority to medium, if it will be reproduced at customer site it should be with critical severity
