### ISSUE TITLE
Bug- launch in entity context (entity text appears twice)

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1038]
**Current behavior** 
 the time between the overlay and the info entity appears twice (same text)
see image-
![image](https://user-images.githubusercontent.com/26301386/34481163-2dc1d4c2-efb9-11e7-9571-5cf1a9730b59.png)
![image](https://user-images.githubusercontent.com/26301386/34481169-397a9ccc-efb9-11e7-9701-3f5233748424.png)

**Expected behavior** 
text should appear only once

**Minimal reproduction of the problem with instructions** 
open the URL
http://ansyn.io:81/#/?context=Info%20Entity&geometry=POLYGON((40.73223283859315%20-73.99867057800293,40.730720648507656%20-73.99556994438171,40.72954989709701%20-73.99656772613525,40.73106211378899%20-73.99962544441223,40.73223283859315%20-73.99867057800293)))&time=2016-11-11T09:25:40…

**Comment by yuvalbl** [comment]
can't reconstruct - link doesn't launch app with info entity
