### ISSUE TITLE
(Bug): Scale bar parameters are not valid on world map with projection of 4326

### ISSUE THREAD

**Issue by yairtawil** [AnSyn/ansyn#1081]

**Comment by asafMasa** [comment]
@carmelorr it is a bug in openlayers https://github.com/openlayers/openlayers/issues/7694
that was fixed a week ago, we are waiting for a new version to be deployed

**Comment by asafMasa** [comment]
https://github.com/openlayers/openlayers/issues/8013

**Comment by ronenru** [comment]
move to new repo
