### ISSUE TITLE
Bug- status bar resolution 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1089]
Please check the status bar (imagery count, middle line and default case) for laptop size resolution.

**Comment by asafMasa** [comment]
@carmelorr @idanbarak High priority os for 0.8 bugs, is this the issue here?

**Comment by idanbarak** [comment]
@asafMasa  yes
@carmelorr  you have to be more specific about the resolution, my laptop some of the company laptops are 1080*1920 and some are 720*1280

**Comment by carmelorr** [comment]
@idanbarak yes i know, i meant to do edit this issue..
