### ISSUE TITLE
As a <User>, I want to <Navigate betwean overlays> so that <i can examine a coordinate throw interveal of time>

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1133]

**Comment by asafMasa** [comment]
Implement according to #784

**Comment by yuvalbl** [comment]
After some discussion we agreed:
1. All calculation will be in absolute time units (1 month = 30 days, etc... *all* units can be converted to ms)
2. Data can be droped to keep time unit consistent (1 year = 12 months  = 360 days, some data may not be included)
3. this feature will function as a filter (althou may not look like one according to UI). that means changing interval size will not send new requests to the server
4. UI is to prevent time scope overlapping (so each "interval" scope will not overlap other intervals)

**Comment by carmelorr** [comment]
Related to https://github.com/AnSyn/ansyn/issues/784

About no. 4 above- we decided to prevent the overlapping by setting the before and after criteria to half the time scope (month=15. days).

**Comment by yuvalbl** [comment]
@carmelorr 
not exactly.

For *Best within" - sum of "before" and "after" should be limited to the size of an interval

For *Closest" - 
when option "doesn't matter" is selected - filter scope is half the time scope (as you described)
when other options (before/after) selected - filter scope is the time scope
@idanbarak please verify this is correct

**Comment by yuvalbl** [comment]
duplicated of #784 
see the conversation about this matter on the original issue thread
