### ISSUE TITLE
Bug- compass and not Geo registered overlay

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1156]
this issue is related to- #960
But for now- please change **only** the  'N' to a question mark and add a tool tip "press Ctrl, Shift, Alt and drag to rotate"   

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/c557991e-de5e-48ae-b095-5979ad9395a7)

**Comment by idanbarak** [comment]
[compass_disabled.svg.zip](https://github.com/AnSyn/ansyn/files/1684904/compass_disabled.svg.zip)

**Comment by carmelorr** [comment]
@yairtawil sorry, please remove the "ctrl" from the tool tip
