### ISSUE TITLE
Determine maximum number of overlays

### ISSUE THREAD

**Issue by MarkShleifer** [AnSyn/ansyn#116]
Timeline component is working well with about ~10,000 overlays as an input.
Due to the fact that the input can contain much more overlays, we should decide how to limit the quantity displayed in the timeline with some kind of level-of-details mechanism or with an UX decision.

**Comment by idanbarak** [comment]
at the moment 10,000 sounds like more than enough..
when the number of overlays excceds 10,000 its ok to not show data in timeline and provide the user with an indication that he need to keep on filtering in order to view data in timeline.
