### ISSUE TITLE
Bug- filters & show only favorites

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1171]
current:
select a few favorite overlays
select show only favorites
check off all of the filters
check off show only favorites
the favorite overlay remains on the time line
![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/45af1b44-996f-4cc5-ae2f-fb773e71a20d)

should be:
no overlays on the time line
notification saying : "no overlays match your query, please try another search"

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/c5ee10b4-f7dc-42cf-bd79-66d69a4d3bd7)

**Comment by yuvalbl** [comment]
@carmelorr 
Seems like FAD

**Comment by yuvalbl** [comment]
@idanbarak @carmelorr 

This seems to work according to design.
can we close this issue?

**Comment by idanbarak** [comment]
@yuvalbl 
yes
