### ISSUE TITLE
Bug - Entity should be positioned by marker bottom edge

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#1175]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
Entity is positioned by marker center

**Expected behavior** 
Entity should be positioned by marker bottom edge

**Minimal reproduction of the problem with instructions** 
1. open link with entity:
http://ansyn.io:81/#/?context=Info%20Entity&geometry=POLYGON((40.73223283859315%20-73.99867057800293,40.730720648507656%20-73.99556994438171,40.72954989709701%20-73.99656772613525,40.73106211378899%20-73.99962544441223,40.73223283859315%20-73.99867057800293)))&time=2015-11-11T09:25:40

2. Zoom in until you see marker inside the green rectangle

3. zoom out, see the marker is pointing outside of the green rectangle

See attachment
![image](https://user-images.githubusercontent.com/11487010/35777736-a62248cc-09bb-11e8-87cf-f3654cb90a56.png)

* **Browser:**
chrome - latest (63)

**Comment by asafMasa** [comment]
@carmelorr @idanbarak is this a real bug?

**Comment by carmelorr** [comment]
@asafMasa yes

**Comment by yuvalbl** [comment]
@asafMasa 
This issue led me to another issue in this matter - 
when we launch the app with entity context we get an error.

seems like this commit cause the issue:
https://github.com/AnSyn/ansyn/commit/25de3d0554f68fcdb05e24604214c302f64352ac

@yairtawil check you check it out?
you can use the following link to reconstruct on dev environment

localhost:4200/#/?context=Info%20Entity&geometry=POLYGON((40.73223283859315%20-73.99867057800293,40.730720648507656%20-73.99556994438171,40.72954989709701%20-73.99656772613525,40.73106211378899%20-73.99962544441223,40.73223283859315%20-73.99867057800293)))&time=2015-11-11T09:25:40

**Comment by yuvalbl** [comment]
There is an open issue in this regard, I'll copy the data to issue #992
