### ISSUE TITLE
Time line- a group of overlays looks flat

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1180]
a group of overlays looks flat. it should be thicker.
after pressing an overlay it is ok. 

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/5255db15-d559-435a-8e26-52dfb0eb5a6c)

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/6a53dbae-5f97-4a13-99a9-13168cfebd5c)

**Comment by shaharido1** [comment]
doplicute
