### ISSUE TITLE
Not Geo registered overlays & digger

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1189]
What to do when "digging" back overlays, but some of them are not Geo registered or not accurately Geo registered? (zoom and location)

**Comment by carmelorr** [comment]
related to #1224

**Comment by idanbarak** [comment]
solved by #1224 
user can filter by geo registration field

**Comment by idanbarak** [comment]
@carmelorr 
if it is fine by you please close the issue
