### ISSUE TITLE
Integration with G system - Insert dependencies and show overlays 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#121]
- [x] Take the current code inside and configurat workspace (packages,sinopia)
- [x] Show overlays from G system

**Comment by ronenru** [comment]
@eldadcohen1 - change this item to an Epic and add separate USs

**Comment by eldadcohen1** [comment]
@asafMasa   please connect to relevant tasks to this US.

**Comment by asafMasa** [comment]
Overlays from g are shown via sand box
