### ISSUE TITLE
Manual Image Enhancement - menu sliders does not change according to active imagery

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1212]
current:
1. open 2 overlays in 2 separate imagery windows
2. Manual Image Enhancement menu - change one of the sliders
3. change active window
4. sliders stays in the same position

expected:
1. open 2 overlays in 2 separate imagery windows
2. Manual Image Enhancement menu - change one of the sliders
3. change active window
4. sliders position should indicate values of current overlay

**Comment by asafMasa** [comment]
@idanbarak duplication of #875
