### ISSUE TITLE
Geo registration failed

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1224]
Please add this notification for cases the overlay is supposed to be Geo registered, but it is really not. 
All other functionality should be the same as for "not Geo registered".
 ![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/6688a819-9cdc-4df5-a79b-7210f835a61b)
![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/152a47e8-5c9b-49da-ace9-63fbff72169d)

**Comment by asafMasa** [comment]
@Danaorlov1005 Please ask yair how to solve this in customer site

**Comment by asafMasa** [comment]
@carmelorr please talk with me about this issue
