### ISSUE TITLE
Bug- moving right/left in the time line leads to unwanted overlay

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1230]
@asafMasa               
this is a customer site bug. please check if you can reproduce. try to move numerous times between the overlays (keyboard) and check the overlays time and location.

**Comment by ronenru** [comment]
Issue moved to [AnSyn/PrivIssues #5](https://github.com/AnSyn/PrivIssues/issues/5) via [**ZenHub**](https://www.zenhub.com/)
