### ISSUE TITLE
Bug- loading map failure should return to previous overlay not base map

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1234]
@asafMasa     as we discussed, this bug is for as soon as possible.

**Comment by asafMasa** [comment]
@yairtawil fixed it in customer site and need to merge the changes to master

**Comment by ronenru** [comment]
Issue moved to [AnSyn/PrivIssues #9](https://github.com/AnSyn/PrivIssues/issues/9) via [**ZenHub**](https://www.zenhub.com/)
