### ISSUE TITLE
Filter menu - quantity indication should be updated according to current filter

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1297]

**Comment by idanbarak** [comment]
@carmelorr 
be aware that i have started working on this issue

**Comment by idanbarak** [comment]
**Main problem** 
Currently the quantity indication is fixed (static) according to the results we get from the providers
We want to fixed that in order to enable the user to make more efficient decisions.

**Needed Improvements**
1. The quantity indication will be re-calculated after each change in the filters selection
2. Options with 0 values will appear and behave as disabled options

for basic inspiration you can check out the B&H website:
https://www.bhphotovideo.com/c/search?ci=6559&N=3878805754& 

for disabled option design, please see: 
https://github.com/AnSyn/ansyn/issues/1153

**Comment by asafMasa** [comment]
![image](https://user-images.githubusercontent.com/18442671/38669845-f580b37c-3e4f-11e8-92b2-c664af72c43c.png)
for example: Sensor Name filter should affect Sensor Type filter
