### ISSUE TITLE
New provider - bugs

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1298]
1. imagery perspective is incorrect - https://github.com/AnSyn/ansyn/issues/1328
~~2. tile loading failure is very common - please see if you can do anything about it~~ - fixed

**Comment by liorze** [comment]
Re/ (2), do you experience issues when you restrict your AOI to California?

**Comment by idanbarak** [comment]
yes, but not too much.
if the problem is only outside California, we should maybe restrict the user to search only there

**Comment by idanbarak** [comment]
3. the year indicated in the label of each overlay is always 2018, regardless off the actual year the imagery was taken
![screen shot 2018-03-26 at 17 49 13](https://user-images.githubusercontent.com/4181572/37913668-1ad4c152-311e-11e8-9995-828b52fae0fd.png)

**Comment by liorze** [comment]
Thanks. (3) happened because you are seeing the publish time instead of the acquiring time.

**Comment by idanbarak** [comment]
4. include the following text along with any Planet imagery:
"Open California Satellite Imagery © 2016 Planet Labs Inc. licensed under CC BY-SA 4.0."

**Comment by idanbarak** [comment]
5. filter the request to California AOI only

**Comment by idanbarak** [comment]
6. Planet API allows maximal paging of 250 overlays - we need to access the first 250 (order by date)
