### ISSUE TITLE
Intervals- bugs

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1325]
I started checking the time intervals, found some bugs: 

*Each hour for last month/ year- it does not show overlays for each hour, and therefore missed overlays (test by comparison to the same parameters without time interval)
*Each month for the last year- why it does not show the latest one from today?
*Each two month for the last year- how does it set the latest? 
*The 'last' section in the advanced menu was disabled (although selected) 
*Design needs some changes

**Comment by idanbarak** [comment]
@yuvalbl @carmelorr 
where can i see it, it's not available on http://ansyn.io:81/#/

**Comment by yuvalbl** [comment]
@asafMasa this is a private version and not released to staging/QA yet
@carmel please close this issue as it is confusing.
use the original thread for this feature until it's release
#784
