### ISSUE TITLE
Improve the UI of the layers manager component

### ISSUE THREAD

**Issue by MarkShleifer** [AnSyn/ansyn#143]
The current UI of the layers manager component is not sufficient and has to improve.
The design should look like the example from Figma as attached.
![datalayers](https://cloud.githubusercontent.com/assets/12406642/26100847/c5f17384-3a37-11e7-94ad-9c896856f9e2.jpg)

**Comment by AmitMY** [comment]
Is this still relevant? I thought we only have 1 tree

**Comment by MarkShleifer** [comment]
Yes, but you can override the style of this tree to make it look better.
