### ISSUE TITLE
overlay copyright indication should be configurable by sensor type

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#1432]
for example: 
sentinel 2 data should include the following label: 
'Copernicus Sentinel data [Year]'

**Comment by ramtob** [comment]
Current configuration format:

    "sourceTypeNotices": [
		{
			"key": "PLANET",
			"value": "blablabla"
		}
    ]
  }

Required configuration format:

    "sourceTypeNotices": 
		{
			"PLANET": {
                           "Default": "blablabla",
                           "Landsat8L1G": "bliblibli",
                           "Sentinel2L1C": "blublublu"
                       }
		}

**Comment by ramtob** [comment]
Linked #1370

**Comment by idanbarak** [comment]
desired configuration:

if 
sensor type = Sentinel2L1C
then 
copyright = ׳Copernicus Sentinel data [Year]'

if 
sensor type = Landsat8L1G  
then
copyright = 'USGS/NASA Landsat Program'

all other sensor types should remain with the current planet copyright indication

**Comment by ramtob** [comment]
I.e. for Sentinel, we add the year of the overlay (not the current year)
