### ISSUE TITLE
(Bug): launch the app with position context doesn't work

### ISSUE THREAD

**Issue by ramtob** [AnSyn/ansyn#1492]
related #1353 

http://ansyn.io:81/#/?context=areaAnalysis&geopoint=33.81265,-117.91897

- gets an error for loading context
- all the sensor types are selected
- although an overlay is being displayed

**Comment by carmelorr** [comment]
@ramtob according to issue #310, the imagery count should be 30,

**Comment by ramtob** [comment]
@carmelorr We currently return only an approximate number of (like this 43) of overlays. This is dependent on the capacities of the providers that we work with. Some of them (like Planet) do not support a query that returns the exact (like this 30) number of overlays, for the conditions of the context.
