### ISSUE TITLE
Bug- hovering the overlays sometimes open the wrong preview

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1495]
open the link and hover the overlays. see the same preview for all overlays. 
 http://ansyn.io:81/#/?facets=(filters:!((fieldName:sensorType,metadata:!(REScene,REOrthoTile,uav,aircraft,satellite),type:Enum),(fieldName:sensorName,metadata:!(RapidEye-4,'DJI Phantom 4','phantom 4 pro','1/2.3” (CMOS), Effective pixels:12.35 M (Total pixels:12.71M)',No,NA,'dji phantom 4','Sony WX',WV03,'Sony A6000','-','Mavic Pro','Sony ILCE-6000',' Sony A6000','FC220_4.7_4000x3000 (RGB)','Sony A6000 + Sony EF 16mm','Mobius Cam',Example,'DJI Phantom 4 Pro','Phantom4 Pro + Agisoft Photoscan','DJI Phantom 4 Pro + Agisoft Photoscan','DJI Mavic Pro Platinum - FC220','DJI mavic','sensefly SODA','DJI Mavic Pro',Drone,'Sensefly Ebee Plus - SODA','DJI Camera',WV02,' WV02','SenseFly Ebee Plus - SODA','Ebbe Sensefly'),type:Enum),(fieldName:sourceType,metadata:!(OPEN_AERIAL),type:Enum),(fieldName:isGeoRegistered,metadata:(displayFalse:!f,displayTrue:!t),type:Boolean)),showOnlyFavorites:!f)&time=(from:'2017-06-05T11:18:16.721Z',to:'2018-06-05T11:18:16.722Z',type:absolute)&maps=(activeMapId:dc48f8b7-4a10-7d45-c241-723b318f9d43,data:!((data:(imageManualProcessArgs:(Brightness:0,Contrast:0,Gamma:100,Saturation:100,Sharpness:0),isAutoImageProcessingActive:!f,overlay:(id:'59e62bb23d6412ef7220af16',sourceType:OPEN_AERIAL),overlayDisplayMode:Polygon,position:(extentPolygon:(coordinates:!(!(!(120.49804687499999,-8.584988862157246),!(120.5360698699951,-8.584988862157246),!(120.5360698699951,-8.620589735768064),!(120.49804687499999,-8.620589735768064),!(120.49804687499999,-8.584988862157246))),type:Polygon),projectedState:(center:!(13415896.828740304,-961274.666703029),projection:(code:'EPSG:3857'),resolution:4.777314267823516,rotation:0,zoom:15))),flags:(),id:defaultImagery1,mapType:openLayersMap),(data:(imageManualProcessArgs:(Brightness:0,Contrast:0,Gamma:100,Saturation:100,Sharpness:0),overlay:(id:'59e62bb13d6412ef7220af02',sourceType:OPEN_AERIAL),position:(extentPolygon:(coordinates:!(!(!(103.46606254577637,-4.8427348872843226),!(103.50408554077148,-4.8427348872843226),!(103.50408554077148,-4.878611371870662),!(103.46606254577637,-4.878611371870662),!(103.46606254577637,-4.8427348872843226))),type:Polygon),projectedState:(center:!(11519903.64361971,-541737.0721405256),projection:(code:'EPSG:3857'),resolution:4.777314267823516,rotation:0,zoom:15))),flags:(),id:dc48f8b7-4a10-7d45-c241-723b318f9d43,mapType:openLayersMap)),layout:layout2)&region=POLYGON ((-141.6796875 69.47296854140572, 66.79687499999999 70.78690984117927, 81.91406249999997 -16.467694748288963, -69.25781250000001 -39.504040705584146, -141.6796875 69.47296854140572))&overlaysManualProcessArgs=('59e62bb13d6412ef7220af02':(Brightness:0,Contrast:0,Gamma:100,Saturation:100,Sharpness:0))&orientation='Align North'

**Comment by asafMasa** [comment]
@carmelorr @idanbarak please define what exactly you want here

**Comment by idanbarak** [comment]
@asafMasa 
see the **right** preview for each overlay all of the time

**Comment by ramtob** [comment]
@idanbarak The issue, I think, is that the preview images are taking time to load. 
When you move the mouse pointer over the overlays drops, we usually cannot load the correct previews fast enough. The question is what to show, considering this. Perhaps a loading animation?
