### ISSUE TITLE
Bug (InfoEntity context): the two maps are not centered on the object

### ISSUE THREAD

**Issue by ramtob** [AnSyn/ansyn#1521]
See http://ansyn.io:81/#/?context=infoEntity&geometry=POLYGON((33.72478425368034%20-117.94049546019673,33.7245817907568%20-117.89277205679224,33.703236413961335%20-117.89392898778387,33.70381487945715%20-117.94000376452529,33.72478425368034%20-117.94049546019673))&time=2018-05-05T09:25:40

Note: the bug does _not_ happen when running master on localhost!

**Comment by carmelorr** [comment]
@asafMasa this is not ready for testing
