### ISSUE TITLE
(enh) Flicker on 'f' button

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1617]
- [x] Mark overlay as "flickered overlay"
- [x] Navigate between "flickered overlay"s by 'f' button

**Comment by carmelorr** [comment]
this button will have the same functionality as the favorites.  the user will be able to choose to "show only _them_", and they will remain available in case there are no other overlays available.

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/43367050-b4cd11a4-934f-11e8-930a-335860f02825.png)
![image](https://user-images.githubusercontent.com/26301386/43367053-c8ef9e4a-934f-11e8-8904-b17b09043262.png)

**Comment by carmelorr** [comment]
@asafMasa also, please change the keyboard to "Q"
