### ISSUE TITLE
(feat) Case Multi-annotation layers

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1620]
- [ ] Add Layer
- [ ] Remove Layer
- [ ] Show relevant Annotations Layers for selected case

**Comment by carmelorr** [comment]
![16](https://user-images.githubusercontent.com/26301386/42821859-30fa4c0a-89e2-11e8-8be4-e8377133f81b.png)

![16 1](https://user-images.githubusercontent.com/26301386/42821854-2e7c471c-89e2-11e8-9a17-e94efc2f838e.png)

![16 2](https://user-images.githubusercontent.com/26301386/42821842-26971c0c-89e2-11e8-8190-793133409834.png)

![image](https://user-images.githubusercontent.com/26301386/42821876-3cba4cfc-89e2-11e8-98cd-6ada7aeac2e5.png)
