### ISSUE TITLE
(definition bug): Measure tool disapears when drawing annotations

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1643]

**Comment by idanbarak** [comment]
@carmelorr

**Comment by carmelorr** [comment]
please add a new annotation to the menu- a measurement annotation. 
this annotation will include lines and text indicating the distant (same as the measurements tool). 
this annotation will also be saved as a layer, and will have the same functions as the rest of the annotations (stroke, width..etc.). 

![image](https://user-images.githubusercontent.com/26301386/43264734-943151d8-90ef-11e8-841e-66be14f377da.png)

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/43366554-69f11088-9348-11e8-9586-5113e9162bcf.png)

![image](https://user-images.githubusercontent.com/26301386/43366603-4cf3739e-9349-11e8-8a5c-2b212877ab52.png)
![image](https://user-images.githubusercontent.com/26301386/43366622-9cce330e-9349-11e8-9e2f-4a929f9978fe.png)

**Comment by carmelorr** [comment]
clicking the measurement icon will show the measurements, click again will hide them.
the measurements will also be available for download as part of the layer.

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/43367425-44b34f0e-9355-11e8-93eb-4950a3113ce1.png)
