### ISSUE TITLE
(bug) can't press on favorites button -> its under the description

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1677]
![image.png](https://images.zenhubusercontent.com/5912eb9151aa2c30577ddab2/5a956af8-5bf0-423b-b848-afc4b7b44cad)

**Comment by asafMasa** [comment]
@carmelorr what is the definition here?

**Comment by carmelorr** [comment]
Buttons should remain available, overlay name should be minimized (A...), since it is also seen  by hover
