### ISSUE TITLE
(enh)  Add label to annotation

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1737]
related to https://github.com/AnSyn/ansyn/issues/818

**Comment by carmelorr** [comment]
@asafMasa do you mean user name or label?

**Comment by carmelorr** [comment]
The user will be able to add a label to each annotation.
The label can include text and numbers.
The label stroke and fill (background) will be in the same color as the annotation. 
The label text input will be the same as the layer/case name input.
The label show/hide will be the same as the measurements- toggle show/hide. 
![7 1 2](https://user-images.githubusercontent.com/26301386/43999276-10df1f1a-9e12-11e8-8bd7-c3849f531438.png)
![7 1 2 3](https://user-images.githubusercontent.com/26301386/43999333-0a537f64-9e13-11e8-9a22-86a8c8aa1a90.png)
![7 1 2 1](https://user-images.githubusercontent.com/26301386/43999277-1b613b9e-9e12-11e8-9579-739adf6b4134.png)
![7 1 2 2](https://user-images.githubusercontent.com/26301386/43999279-240fc670-9e12-11e8-82ee-72f3f4e010e2.png)
