### ISSUE TITLE
Bug- remove overlay from case

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1744]
When an overlay is removed from the case it should not be shown on the screen anymore.
Instead please show the previous overlay or the base map if there was no previous overlay.

**Comment by asafMasa** [comment]
@carmelorr @idanbarak can we just go back to world? it's mutch more simple and intuative

**Comment by asafMasa** [comment]
need to remove dro favorites, quik loop and prev/next functionality
