### ISSUE TITLE
Bug- remove overlay from case and next/prev overlays

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1746]
After an overlay is removed from the case (the previous overlay should be shown)
and the navigation to next/prev overlay should be as always (from the active overlay).
The current behavior- after an overlay is removed, there is no previous overlay- the navigation (next/prev) begins from the first overlay in the time line (regardless of when the removed overlay was).

**Comment by asafMasa** [comment]
related to #1744
