### ISSUE TITLE
Preview- failed to find overlay preview

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1748]
In case no overlay preview is available- what should the user see?

a preview window with a default image and a notification? TBD

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/b092bfde-f214-4bd3-80d2-ef14e232c99d)

**Comment by asafMasa** [comment]
@carmelorr @idanbarak please finish this desing fast, as we need it

**Comment by carmelorr** [comment]
In case a preview image is not available please add this notification along with the overlay details on the bottom. 
![2 15 1](https://user-images.githubusercontent.com/26301386/44309400-a7497600-a3ce-11e8-9e9e-83606d659166.png)
