### ISSUE TITLE
Overlays from Open Aerial are  sometimes out of the Geo filter

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1799]
See search polygon and overlay location-
![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/97de0cfd-70c8-4d90-b184-cf39ea1ac018)

{"_id":"5ad0fb2191b5310010e0d501","acquisition_end":"2018-04-10T22:00:00.000Z","acquisition_start":"2018-04-10T21:00:00.000Z","contact":"Ivan Petrushev,ivanatora@gmail.com","platform":"uav","provider":"Ivan Petrushev","properties":{"license":"CC-BY 4.0","sensor":"FC220","crs":"EPSG:4326","dimensions":[15715,18508],"url":"s3://oin-hotosm/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe.tif","bands":3,"resolution_in_meters":0.0635118806007,"filename":"5ad0fa2891b5310010e0d4fe.tif","dtype":"uint8","colorinterp":["red","green","blue"],"resolution":[5.711760645674246e-7,4.2502813197806686e-7],"thumbnail":"https://oin-hotosm.s3.amazonaws.com/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe.png","tms":"https://tiles.openaerialmap.org/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe/{z}/{x}/{y}.png","wmts":"https://tiles.openaerialmap.org/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe/wmts"},"title":"Cemetery West","user":{"_id":"5a27a6f631eff4000c380688","name":"Ivan Petrushev"},"uuid":"https://oin-hotosm.s3.amazonaws.com/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe.tif","geojson":{"type":"MultiPolygon","coordinates":[[[[24.763387,42.153387],[24.763387,42.153345],[24.763444,42.153345],[24.763444,42.153387],[24.763387,42.153387]]],[[[24.770076,42.148199],[24.770076,42.148157],[24.770304,42.148157],[24.770304,42.148199],[24.770076,42.148199]]],[[[24.76453,42.154025],[24.76453,42.153982],[24.764473,42.153982],[24.764244,42.153982],[24.764244,42.15377],[24.764187,42.15377],[24.76413,42.15377],[24.76413,42.153812],[24.763958,42.153812],[24.763958,42.15377],[24.764015,42.15377],[24.764015,42.153727],[24.763958,42.153727],[24.763958,42.1536],[24.763901,42.1536],[24.763844,42.1536],[24.763844,42.153557],[24.763787,42.153557],[24.763787,42.153515],[24.76373,42.153515],[24.76373,42.153472],[24.763672,42.153472],[24.763672,42.153387],[24.763615,42.153387],[24.763615,42.153345],[24.763558,42.153345],[24.763501,42.153345],[24.763501,42.15326],[24.763444,42.15326],[24.763444,42.153217],[24.763387,42.153217],[24.763387,42.153175],[24.763329,42.153175],[24.763272,42.153175],[24.763272,42.153132],[24.763215,42.153132],[24.763215,42.153089],[24.763158,42.153089],[24.763158,42.153047],[24.763101,42.153047],[24.763101,42.152537],[24.763044,42.152537],[24.762872,42.152537],[24.762872,42.152452],[24.762815,42.152452],[24.762815,42.147391],[24.762872,42.147391],[24.762872,42.147264],[24.763101,42.147264],[24.763101,42.147051],[24.763158,42.147051],[24.763158,42.146966],[24.763215,42.146966],[24.763215,42.146924],[24.763272,42.146924],[24.763272,42.146881],[24.763387,42.146881],[24.763387,42.146711],[24.763672,42.146711],[24.763672,42.146626],[24.763787,42.146626],[24.763787,42.146499],[24.763844,42.146499],[24.763844,42.146456],[24.763901,42.146456],[24.763901,42.146413],[24.763958,42.146413],[24.763958,42.146286],[24.764015,42.146286],[24.764015,42.146201],[24.764473,42.146201],[24.764473,42.146158],[24.765959,42.146158],[24.765959,42.146201],[24.766302,42.146201],[24.76636,42.146201],[24.76636,42.146328],[24.766588,42.146328],[24.766645,42.146328],[24.766645,42.146499],[24.766874,42.146499],[24.766931,42.146499],[24.766931,42.146626],[24.766988,42.146626],[24.766988,42.146669],[24.767046,42.146669],[24.767046,42.146626],[24.76716,42.146626],[24.76716,42.146669],[24.767446,42.146669],[24.767503,42.146669],[24.767503,42.146754],[24.76756,42.146754],[24.76756,42.146839],[24.767617,42.146839],[24.767617,42.146881],[24.767674,42.146881],[24.767674,42.146839],[24.767732,42.146839],[24.767789,42.146839],[24.767789,42.147136],[24.768018,42.147136],[24.768075,42.147136],[24.768075,42.147349],[24.768361,42.147349],[24.768418,42.147349],[24.768418,42.147562],[24.768532,42.147562],[24.768589,42.147562],[24.768589,42.147647],[24.768646,42.147647],[24.768704,42.147647],[24.768704,42.147774],[24.768761,42.147774],[24.768761,42.147732],[24.769333,42.147732],[24.76939,42.147732],[24.76939,42.147859],[24.769447,42.147859],[24.769447,42.147774],[24.769676,42.147774],[24.769676,42.147817],[24.769733,42.147817],[24.76979,42.147817],[24.76979,42.147902],[24.769847,42.147902],[24.769847,42.147944],[24.769904,42.147944],[24.769904,42.148029],[24.770019,42.148029],[24.770019,42.147944],[24.770076,42.147944],[24.770133,42.147944],[24.770133,42.148114],[24.770076,42.148114],[24.770076,42.148072],[24.770019,42.148072],[24.770019,42.148242],[24.770304,42.148242],[24.770304,42.148199],[24.770362,42.148199],[24.770419,42.148199],[24.770419,42.148284],[24.770362,42.148284],[24.770362,42.148327],[24.770419,42.148327],[24.770419,42.148369],[24.770476,42.148369],[24.770476,42.148497],[24.770419,42.148497],[24.770419,42.148582],[24.770476,42.148582],[24.770533,42.148582],[24.770533,42.148667],[24.770647,42.148667],[24.770705,42.148667],[24.770705,42.148795],[24.770876,42.148795],[24.770876,42.148752],[24.770933,42.148752],[24.770991,42.148752],[24.770991,42.148837],[24.771048,42.148837],[24.771048,42.14905],[24.771105,42.14905],[24.771105,42.149092],[24.771162,42.149092],[24.771219,42.149092],[24.771219,42.14922],[24.771562,42.14922],[24.771619,42.14922],[24.771619,42.149518],[24.771734,42.149518],[24.771791,42.149518],[24.771791,42.14973],[24.771734,42.14973],[24.771734,42.149943],[24.771791,42.149943],[24.771791,42.151941],[24.771734,42.151941],[24.771734,42.151984],[24.771791,42.151984],[24.771791,42.152622],[24.771734,42.152622],[24.771734,42.152707],[24.771791,42.152707],[24.771791,42.152792],[24.771734,42.152792],[24.771734,42.152877],[24.771677,42.152877],[24.771677,42.152919],[24.771619,42.152919],[24.771619,42.153387],[24.771334,42.153387],[24.771334,42.1536],[24.771219,42.1536],[24.771219,42.153642],[24.771276,42.153642],[24.771334,42.153642],[24.771334,42.153812],[24.771162,42.153812],[24.771162,42.153727],[24.771105,42.153727],[24.771105,42.15377],[24.771048,42.15377],[24.771048,42.153812],[24.770991,42.153812],[24.770991,42.154025],[24.766131,42.154025],[24.766131,42.153982],[24.766188,42.153982],[24.766188,42.15394],[24.766074,42.15394],[24.766074,42.154025],[24.76453,42.154025]],[[24.763329,42.152579],[24.763387,42.152579],[24.763387,42.152537],[24.763329,42.152537],[24.763329,42.152579]],[[24.762929,42.152452],[24.763101,42.152452],[24.763101,42.152409],[24.763044,42.152409],[24.762986,42.152409],[24.762986,42.152367],[24.762929,42.152367],[24.762929,42.152452]],[[24.771619,42.152196],[24.771619,42.152154],[24.771677,42.152154],[24.771677,42.152196],[24.771619,42.152196]],[[24.762929,42.147732],[24.762986,42.147732],[24.762986,42.147689],[24.762929,42.147689],[24.762929,42.147732]],[[24.768932,42.147859],[24.769218,42.147859],[24.769218,42.147817],[24.768932,42.147817],[24.768932,42.147859]],[[24.764587,42.15394],[24.764587,42.153897],[24.764702,42.153897],[24.764702,42.15394],[24.764587,42.15394]]]],"bbox":[24.762815,42.146158,24.771791,42.154025]},"footprint":"POLYGON ((24.762815 42.146158, 24.771791 42.146158, 24.771791 42.154025, 24.762815 42.154025, 24.762815 42.146158))","gsd":0.0635118806007,"file_size":37840470,"projection":"GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]]","meta_uri":"https://oin-hotosm.s3.amazonaws.com/5ad0fa2891b5310010e0d4fd/0/5ad0fa2891b5310010e0d4fe_meta.json","uploaded_at":"2018-04-13T18:46:57.130Z","__v":0,"bbox":[24.762815,42.146158,24.771791,42.154025]}

**Comment by carmelorr** [comment]
it happens a lot. here's another example-

![image](https://user-images.githubusercontent.com/26301386/45262244-ef7f1580-b41b-11e8-804a-a95c2a8f7932.png)

{"_id":"5b6d82e0894c288c1e792e02","acquisition_end":"2018-08-08T17:00:00.000Z","acquisition_start":"2018-08-07T15:00:00.000Z","contact":"Artem  V,artem@veikus.com","platform":"uav","provider":"Artem V","properties":{"wmts":"https://tiles.openaerialmap.org/5b6d8203894c283e5b792e00/0/5b6d8203894c287daa792e01/wmts","tms":"https://tiles.openaerialmap.org/5b6d8203894c283e5b792e00/0/5b6d8203894c287daa792e01/{z}/{x}/{y}","thumbnail":"https://oin-hotosm.s3.amazonaws.com/5b6d8203894c283e5b792e00/0/5b6d8203894c287daa792e01.png","sensor":"DJI Mavic Pro","license":"CC-BY 4.0"},"title":"Kyiv, Patriotika (1)","user":{"_id":"5b68b0054b873674cbf0fa6a","name":"Artem  V"},"uuid":"https://oin-hotosm.s3.amazonaws.com/5b6d8203894c283e5b792e00/0/5b6d8203894c287daa792e01.tif","geojson":{"type":"MultiPolygon","coordinates":[[[[30.624092,50.3868],[30.624094,50.386759],[30.624158,50.386761],[30.624155,50.386801],[30.624092,50.3868]]],[[[30.623567,50.390902],[30.623736,50.387526],[30.623863,50.387528],[30.623861,50.387569],[30.624053,50.387573],[30.624088,50.386881],[30.624151,50.386883],[30.624155,50.386801],[30.624219,50.386802],[30.624221,50.386762],[30.624349,50.386764],[30.624388,50.385991],[30.624452,50.385993],[30.624468,50.385667],[30.624404,50.385666],[30.624426,50.385219],[30.62449,50.38522],[30.624496,50.385098],[30.62456,50.385099],[30.624562,50.385058],[30.62469,50.385061],[30.624688,50.385102],[30.624943,50.385107],[30.624945,50.385066],[30.629224,50.385154],[30.629222,50.385194],[30.629669,50.385203],[30.629733,50.385205],[30.629715,50.385571],[30.630226,50.385581],[30.630289,50.385582],[30.630287,50.385623],[30.630734,50.385632],[30.630736,50.385592],[30.630992,50.385597],[30.63099,50.385637],[30.632331,50.385665],[30.632333,50.385624],[30.633546,50.385649],[30.633544,50.38569],[30.633608,50.385691],[30.633602,50.385813],[30.633666,50.385814],[30.633658,50.385977],[30.633594,50.385976],[30.633588,50.386098],[30.634163,50.386109],[30.634227,50.386111],[30.634216,50.386314],[30.63428,50.386315],[30.634278,50.386356],[30.634342,50.386357],[30.634344,50.386317],[30.634472,50.386319],[30.634536,50.386321],[30.634526,50.386524],[30.6351,50.386536],[30.635164,50.386537],[30.63516,50.386618],[30.635224,50.38662],[30.635288,50.386621],[30.635286,50.386662],[30.63535,50.386663],[30.635352,50.386622],[30.635416,50.386624],[30.635479,50.386625],[30.635455,50.387113],[30.635519,50.387114],[30.635515,50.387196],[30.635707,50.3872],[30.63577,50.387201],[30.635696,50.388706],[30.635632,50.388705],[30.635634,50.388664],[30.635506,50.388662],[30.635504,50.388702],[30.635376,50.3887],[30.63536,50.389025],[30.635424,50.389026],[30.635414,50.38923],[30.63535,50.389228],[30.635342,50.389391],[30.635406,50.389392],[30.635402,50.389474],[30.635338,50.389473],[30.635322,50.389798],[30.635385,50.389799],[30.635381,50.389881],[30.635318,50.389879],[30.635313,50.389961],[30.635122,50.389957],[30.635124,50.389916],[30.634741,50.389908],[30.634737,50.38999],[30.634673,50.389988],[30.634669,50.39007],[30.634733,50.390071],[30.634718,50.390356],[30.634655,50.390355],[30.634644,50.390558],[30.634708,50.390559],[30.6347,50.390722],[30.634509,50.390718],[30.634507,50.390759],[30.634315,50.390755],[30.634307,50.390918],[30.634051,50.390912],[30.634041,50.391116],[30.631295,50.39106],[30.631305,50.390857],[30.631241,50.390855],[30.631245,50.390774],[30.631181,50.390773],[30.631177,50.390854],[30.630986,50.39085],[30.630994,50.390687],[30.63093,50.390686],[30.630419,50.390676],[30.630421,50.390635],[30.630293,50.390632],[30.630291,50.390673],[30.6301,50.390669],[30.630102,50.390628],[30.629718,50.390621],[30.629716,50.390661],[30.628567,50.390638],[30.628569,50.390597],[30.628505,50.390596],[30.628503,50.390637],[30.628439,50.390635],[30.628441,50.390595],[30.628377,50.390593],[30.628375,50.390634],[30.628311,50.390633],[30.628313,50.390592],[30.628186,50.390589],[30.628165,50.390996],[30.627974,50.390992],[30.627994,50.390585],[30.627866,50.390583],[30.627846,50.39099],[30.623567,50.390902]],[[30.624211,50.386965],[30.624275,50.386967],[30.624277,50.386926],[30.624213,50.386925],[30.624211,50.386965]],[[30.627932,50.390543],[30.627934,50.390503],[30.627998,50.390504],[30.627996,50.390545],[30.627932,50.390543]],[[30.634397,50.39039],[30.634525,50.390393],[30.634527,50.390352],[30.634399,50.390349],[30.634397,50.39039]],[[30.631618,50.385854],[30.631624,50.385732],[30.632263,50.385745],[30.632257,50.385867],[30.631618,50.385854]]]],"bbox":[30.623567,50.385058,30.63577,50.391116]},"footprint":"POLYGON ((30.623567 50.385058, 30.63577 50.385058, 30.63577 50.391116, 30.623567 50.391116, 30.623567 50.385058))","gsd":0.04523,"file_size":41013027,"projection":"PROJCS[\"WGS 84 / UTM zone 36N\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",33],PARAMETER[\"scale_factor\",0.9996],PARAMETER[\"false_easting\",500000],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],AUTHORITY[\"EPSG\",\"32636\"]]","meta_uri":"https://oin-hotosm.s3.amazonaws.com/5b6d8203894c283e5b792e00/0/5b6d8203894c287daa792e01_meta.json","uploaded_at":"2018-08-10T12:19:44.059Z","__v":0,"bbox":[30.623567,50.385058,30.63577,50.391116]}

**Comment by ramtob** [comment]
@carmelorr @asafMasa The current situation seems to be because Open Aerial does not accept just any polygon for search, but only boxes (straight rectangles). We send them the bounding box of the selected polygon. This is why we get search result outside the polygon.

![image](https://user-images.githubusercontent.com/11027714/46916714-ec50e980-cfc6-11e8-8a74-078f01fc7150.png)
