### ISSUE TITLE
Bug- no overlays on startup

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1815]
start up the APP

see no overlays available.

overlays are available after re-search the same date and location

**Comment by carmelorr** [comment]
@asafMasa could be related to #1816

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/46255499-58e7c680-c4a6-11e8-997b-03e536185d93.png)

**Comment by asafMasa** [comment]
Duplicate same as #1816
