### ISSUE TITLE
(bug) check/uncheck favorite doesn't refresh time-line icon

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1822]
## Steps to reproduce:
1. Display an overlay
2. move to a location outside of the overlay, and invoke there a search
(now the overlay is not displayed on the timeline)
3. mark the overlay as favorite
result: the overlay is still not displayed on the timeline
this is incorrect

**Comment by ramtob** [comment]
A new action plan @asafMasa @yairtawil 
* Overlays and filteredOverlays will be criterial, and therefore, unlike now, will not include non-criterial favorites
* Drops will combine criterial and non-criterial overlays: overlays, filteredOverlays, favoriteOverlays, showOnlyOverlays
* We will not update the drops, like now, in overlays.reducer. Drops will listen to latest values of several fields, some of them not in overlays pkg.
* So, we will add an effect (updateOverlayDrops$) to filters.app.effects, under the existing effect (updateOverlayFilters$) which updates filteredOverlays
* This new effect will dispatch a new action SET_DROPS which will trigger a simple assignment in the reducer
* We will leave, for now, favoriteOverlays in Core module. And therefore no change will be need in imagery-status component
* removeOverlays will get into the build of filteredOverlays, as now
* In overlays.effects, effect loadOverlays$, we will cancel the addition of favoriteOverlays to overlays
