### ISSUE TITLE
Make sure the App fully supports Wgs84 coordinates.  

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#1837]
@asafMasa @idanbarak according to the client by the end of this year the app needs to fully (and mainly) support wgs84 coordinates.

**Comment by asafMasa** [comment]
@carmelorr what do you mean? we already fully support wgs84

**Comment by carmelorr** [comment]
@asafMasa wgs84 should be the default coordinates

**Comment by asafMasa** [comment]
@carmelorr  it is, i don't understand this task
