### ISSUE TITLE
(bug) labels exported by KML format aren't imported

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1879]
check if KML supports label's and implment by it
if not ask @idanbarak what the solution should be

**Comment by ramtob** [comment]
@idanbarak Is there still a problem? If there is, please provide a description how to reproduce the problem.

**Comment by idanbarak** [comment]
I believe KML do support labels.
At the moment when i save an annotation with a label -> export it -> import it -> the label is missing

**Comment by ramtob** [comment]
Saving an annotation with label _from Ansyn_, and then importing it? It works for me.
