### ISSUE TITLE
(enh) ansyn provider backend: add option to fetch images by type

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1893]
- [ ] Raster
- [ ] Vector
- [ ] Image
- [ ] All

**Comment by idanbarak** [comment]
@asafMasa @dafnaweiss 
I think we should also be able to fetch data by other attributes - for example: Sensor name, Sensor type

**Comment by dafnaweiss** [comment]
I add 2 API's in the swagger:
1. get layers by sensor type ('UAV' ,...)
2. get layers by sensor name ('FC6310' - the name of the drone Model)
there is no need (for now) to search by the layer Type (raster/vector/image)
