### ISSUE TITLE
(bug) "remove overlay" when displayed on 2 - more maps

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#1932]
@carmelorr what do you want to happen in this situation?

**Comment by asafMasa** [comment]
@ramtob by carmel one should disapear and the other will have the alert of "not part of query"

**Comment by carmelorr** [comment]
@asafMasa please mind that the current behavior is not according to the design. Now all of them disappears, when only one should disappear and the rest should get "not part of the query" alert.
