### ISSUE TITLE
(Bug) -  "Last Modified" is not updated correctly

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2075]
**Steps to reproduce [Bug 1]**

* Come to the case

**expected [Bug 1]**

* expected the date to stay unchanged

**Actually [Bug 1]**

* Date updated by login

-------------------------------------------------------------------------------------------------------------------

**Steps to reproduce [Bug 2]**

* Create changes In the case And will move on to another case

**Expected [Bug 2]**

* Expected the date will update according to the changes I've made

**Actually [Bug 2]**

* Date did not change according to the changes I've made , The date remains according to the last entry

**Comment by asafMasa** [comment]
@yairtawil @carmelorr say's that a case shouldn't be updated if we just opened it, please to explain her the technical problem and suggest a solution
