### ISSUE TITLE
Images with poor Geo registration

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#2091]
@asafMasa as we discussed, please see notification for images with poor Geo registration.

please mind that all the functions should be the same as images with good Geo registration. 

Also, please make sure that it is a part of the API for the component. 

![image.png](https://images.zenhubusercontent.com/592bc36751aa2c30577fb56b/5c6dc405-fd60-4bba-b9e7-360cf57260ca)

**Comment by asafMasa** [comment]
@ramtob we need to change the flag isGeoRegistered in the overlay class to enum
NotGeoRegistered
GeoRegistered
PoorlyGeoRegistered

the icon will change by the enum state
