### ISSUE TITLE
(bug) - (component) - 'Share Link' does not work in the component

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2101]
**Steps to reproduce**

* Open the component with URL ("https://ansyn.github.io/angular-ansyn-implementation/") , Create changes and click share link , Sign in with the link you copied

**expected**

* The link will open like the link you copied

**Actually**

* The component will open without the changes you created

**Comment by asafMasa** [comment]
@carmelorr what do you want us to do with this issue?
