### ISSUE TITLE
Design of facets + design review

### ISSUE THREAD

**Issue by MarkShleifer** [AnSyn/ansyn#211]

**Comment by carmelorr** [comment]
- General requirement- the ability to define the facets order of appearance

- Set facets types to designated commands

**Comment by idanbarak** [comment]
@carmelorr please update design to include indication on filters sidebar icon to amount of active filters (facets)

![screen shot 2017-06-26 at 16 01 39](https://user-images.githubusercontent.com/4181572/27540408-c6c52032-5a88-11e7-95e3-2977b21353c8.png)
