### ISSUE TITLE
(feature): how to change map types in app

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#2116]
- [ ] Cesium -> OL
- [ ] OL -> Cesium

3D?
2D?
terrain?
DTM?
planet / other images?

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/56572407-ad2fd080-65c7-11e9-8862-9c12cb8ae7cc.png)

**Comment by asafMasa** [comment]
@carmelorr can you please explain the meaning of the buttons?
will other cesium modes (2D, Columbus View etc.) will be supported?
How to switch back to OL?

**Comment by carmelorr** [comment]
@asafMasa at the moment Open layers = 2D and Cesium = 3D (with no 2D and Columbus view).
The user will be able to change between the maps by selecting 2D / 3D mode. 
In addition, please remove the cesium menus from the map. 
![image](https://user-images.githubusercontent.com/26301386/57211401-d0f00f00-6fe8-11e9-8149-66ce6ff27e8a.png)
Please mind that the selected map type should be save in the app case and state (share link). and all other features (annotations, measurements, shadow mouse, etc. ) should work the same.

**Comment by asafMasa** [comment]
@carmelorr i still don't understand where the 2D and 3D buttons will be located, is it as in the first picture? what is the meaning of the + - buttons?

**Comment by asafMasa** [comment]
https://github.com/AnSyn/ansyn/pull/2280
