### ISSUE TITLE
Bug - Exception handling for internal server error

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#216]
* bug report 

**Current behavior** 
- Select case from cases list.
- Request for overlays sends to the serve.
- From some reason the server throw "internal server error"
- You cant select other case and there is no notification about the error.
**Expected behavior**  @idanbarak 
- Continue navigating between cases

**Minimal reproduction of the problem with instructions** 
- Select case from cases list.
- Request for overlays sends to the serve.
- From some reason the server throw "internal server error"
- You cant select other case and there is no notification about the error.

**What is the motivation / use case for changing the behavior?** 
Continue working on other cases

**Comment by idanbarak** [comment]
@carmelorr 
please add expected behavior
