### ISSUE TITLE
(enh) better measurement tools

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#2237]
@carmelorr please define what kind of improvements you want to add (larger text? closing the measure tool? etc.)

**Comment by carmelorr** [comment]
The improvements include: 
1. the addition of a window that opens up every time the user presses the measurements button.
this window will allow the user to "clear" all the measurements, but still remain in an active measurements status. and a "done" button that will allow the user to turn off the measurements tool. 
See image attached: 
![6 3](https://user-images.githubusercontent.com/26301386/57220409-e9215780-7003-11e9-800a-329d8ccc8073.png)

2. The measurements text - should be similar to the annotations measurements: the text should have a black stroke and should appear in the middle of the line (as opposed to the appearance in the edges). see images attached:    
![image](https://user-images.githubusercontent.com/26301386/57220290-74e6b400-7003-11e9-8cc3-020fa889fdfd.png)
![image](https://user-images.githubusercontent.com/26301386/57220890-aa8c9c80-7005-11e9-8e31-34d185de5adf.png)
