### ISSUE TITLE
Case is not saving data layer

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#2256]
1. add the attached data layer
2. save the case
3. get en error in toast
4. open the case
5. layer is not avaliable

**Comment by idanbarak** [comment]
[DAMAGED BUILDINGS.geojson.zip](https://github.com/AnSyn/ansyn/files/3130357/DAMAGED.BUILDINGS.geojson.zip)

**Comment by asafMasa** [comment]
413 (Payload Too Large)

**Comment by asafMasa** [comment]
![image](https://user-images.githubusercontent.com/18442671/58380473-29984380-7fba-11e9-9b7b-bddf57c2b5a1.png)
