### ISSUE TITLE
A problematic case - crashes the app after opening

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#2258]
http://platform.ansyn.io/#/case/60a5757e-ba1c-0397-1f9e-790fb038e6b8

**Comment by asafMasa** [comment]
![image](https://user-images.githubusercontent.com/18442671/57019915-747ba100-6c30-11e9-9221-9b399a0cbf90.png)
its because we have unsupported old "isGeoRegistered" filter that is defined as bool instead of enum

@idanbarak i recommend to delete this case
