### ISSUE TITLE
(bug) - (Component) - When you open image, you do not have access to the Minimize button

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2307]
**Steps to produce**

Open the component "https://ansyn.github.io/angular-ansyn-implementation/" 
and then open some image

**Expected**

You will still have access to the minimize button

![image](https://user-images.githubusercontent.com/46754845/58547384-ed5e2080-820f-11e9-96f7-681bd6169317.png)

**Actually**

you do not have access to the Minimize button

![image](https://user-images.githubusercontent.com/46754845/58546970-2b0e7980-820f-11e9-872a-48239f10c644.png)

**Comment by asafMasa** [comment]
@carmelorr what should we do with the attribution?

**Comment by asafMasa** [comment]
@carmelorr what is the design for this use-case?

**Comment by carmelorr** [comment]
Please move the overlay name up (above the minimize button)
