### ISSUE TITLE
Bug: image source fails to open from timeline with no notification to the user

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#231]
- [X] bug report 

**Expected behavior**
- load image source from timeline
- image fails to be loaded
- App alerts the user of its failure

**Actual behavior**
- app throws un exception (404) and doesn't alert the user

**Comment by osadan** [comment]
@asafMasa It should be handled in the map provide since the overlays doesn't loading the image

**Comment by idanbarak** [comment]
Indicate failure to user using a toast component (see attached image - same one @yairtawil  used in order to indicate that the link url is copied to clipboard)

**Comment by idanbarak** [comment]
![screen shot 2017-09-17 at 13 26 56](https://user-images.githubusercontent.com/4181572/30519964-2708b544-9bac-11e7-80f5-50ecf60d68e2.png)

**Comment by idanbarak** [comment]
indication = "Failed to load overlay"

add icon button before text

**Comment by idanbarak** [comment]
[alert.svg.zip](https://github.com/AnSyn/ansyn/files/1308997/alert.svg.zip)

**Comment by asafMasa** [comment]
@idanbarak i think "Failed to load **image**" is better because in customer site there are other images to load

**Comment by idanbarak** [comment]
@asafMasa 
I think overlay is a general term for an image in the system. for example we have a "Display Overlays" button in the tools menu - it refers to all of the imagery available, even if it is not an actual overlay. as i see it using two terms to describe an image would be confusing for the user

**Comment by idanbarak** [comment]
@eldadcohen1 @asafMasa 
This task is relevant to the main app, not only to customer site.
i have reopened the task

**Comment by eldadcohen1** [comment]
@asafMasa Please add explanation on we should handle   (Openlayers error)

**Comment by asafMasa** [comment]
We handled a case were the layer creation failed, now the layer creation is valid but the image url searched by Open Layer is invalid.
This is a bug inside openlayers layer loading mechanism and need to be researched further.

**Comment by carmelorr** [comment]
The current notification is "No source loader for openLayersMap/IDAHO2" 
@idanbarak what do you think?
