### ISSUE TITLE
(bug) - (component) - The minimize button is not in the middle, and he hides the 'floating coordinates'

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2310]
**Steps to produce**

Open the component "https://ansyn.github.io/angular-ansyn-implementation/" 
and then split the screen into 2 windows (Just to get perspective)

**Expected**

The minimize button will be in the middle

**Actually**

The button is not in the middle it turns to the right side ,and he hides the 'floating coordinates' 

![image](https://user-images.githubusercontent.com/46754845/58635175-df82cb00-82f5-11e9-8b88-0b4e5ba54bb9.png)

**Comment by asafMasa** [comment]
@carmelorr should it be in the exact middle? do you want us to change the position?

**Comment by asafMasa** [comment]
@carmelorr what is the design for this use-case?

**Comment by carmelorr** [comment]
Please see issue https://github.com/AnSyn/ansyn/issues/2363
