### ISSUE TITLE
(bug) - The search line in filters infects groups and not individuals

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2322]
**Steps to produce**

Open the Filters menu and enter name of existing filter in the search bar

**Expected**

You will only receive filters that the letters you searched for will appear in them

**Actually**

You will receive the entire set of filters in which the filter you were looking for is located

![image.png](https://images.zenhubusercontent.com/5c46ec3ab0c6b33edb491848/69fb5e7b-beab-4fd1-8449-d5b71fd81ab9)

**Comment by asafMasa** [comment]
@carmelorr @yairtawil is this a bug or a feature?
