### ISSUE TITLE
(enh) export map image to file

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#2346]

**Comment by asafMasa** [comment]
@carmelorr button location? svg?

**Comment by asafMasa** [comment]
https://openlayers.org/en/latest/examples/export-pdf.html
https://openlayers.org/en/latest/examples/export-map.html

**Comment by carmelorr** [comment]
Please check the option to export all 4 screens as they are in the app

**Comment by tltk90** [comment]
https://github.com/AnSyn/ansyn/issues/2368
