### ISSUE TITLE
(bug) - (component) - The "add features" button does not work

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#2394]
**Steps to reproduce** 
 
https://ansyn.github.io/angular-ansyn-implementation/

Press on "Add features"
![image](https://user-images.githubusercontent.com/46754845/59588337-0ca1ec80-90f0-11e9-8740-8aff7d3fc6e8.png)

**Expected**

Some  annotations will be drawn on the map

**Actually**

nothing's happening

**Comment by asafMasa** [comment]
it works but to a different location (disnyland)
