### ISSUE TITLE
As a <User>, I want to <select favorite overlays per case> so that <i can find them easily>. 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#241]
- user story
- [x] @idanbarak  need's to define the favorites functionality
- [ ] navigation between favorite overlays
- [x] refresh app and display favorite overlays
- [x] save favorites overlays

**Comment by carmelorr** [comment]
favorites functionality-
overlay- when the overlay is in selection, mark as favorite in the status bar
facet- mark as favorite, and filter to show only favorites

favorites' indication on the map and timeline- TBD,probably yellow glow

**Comment by carmelorr** [comment]
![5 3](https://user-images.githubusercontent.com/26301386/27340296-d5142b06-55e2-11e7-989f-58a14f3e4b38.png)
![5 4](https://user-images.githubusercontent.com/26301386/27340298-d51b62a4-55e2-11e7-8c34-dec6113014ee.png)
![5 5](https://user-images.githubusercontent.com/26301386/27340297-d51a2312-55e2-11e7-9442-b19f799bf3cf.png)

**Comment by idanbarak** [comment]
@carmelorr

**Comment by idanbarak** [comment]
@carmelorr 
a few small changes:
**filters menu** - favorites filter should be visually separated from other facets, no headline is needed - only a checkbox and "show only favorites" string

**Yellow glow** - define in css terms

thanks

**Comment by carmelorr** [comment]
yellow glow-
box-shadow: -5px 0px 4px #E8FF4F, 0px -5px 4px #E8FF4F, 5px 0px 4px #E8FF4F, 0px 5px 4px #E8FF4F;

**Comment by carmelorr** [comment]
![5 4 1](https://user-images.githubusercontent.com/26301386/27384080-36addbf6-5696-11e7-9635-7c94ddcc8e78.png)

**Comment by carmelorr** [comment]
#198
