### ISSUE TITLE
Switching between map states (world view - mosaic - local mosaic - frame)

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#252]

**Comment by carmelorr** [comment]
switching between map states- 

"switching in" (from world view to mosaic - local mosaic - frame) is by selecting (clicking) the wanted layout . switching between mosaic - local mosaic - frame is by zooming in.

"switching out" ( from mosaic - local mosaic - frame to world view) is by pressing a designated button. see attached files

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/27260410-4fc2087e-5434-11e7-83dc-75ef4f5ed01c.png)
![image](https://user-images.githubusercontent.com/26301386/27260416-6712b44c-5434-11e7-983b-7291f3ba16ae.png)

**Comment by eldadcohen1** [comment]
@asafMasa Please see the comments
Open new issue on this and develop it.
If you have more questions you can talk with me
