### ISSUE TITLE
map annotations

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#273]
#170

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28308628-7a025c0a-6baf-11e7-916d-1170f83ab8db.png)
![image](https://user-images.githubusercontent.com/26301386/28308649-8c6d69e8-6baf-11e7-91c7-1c46684bf17a.png)

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28372658-fae79106-6ca8-11e7-99f3-52b4566386d3.png)

**Comment by carmelorr** [comment]
Annotation via layers #269 #209 
Pressing the annotation button opens a new layer automatically?  All the annotations are on the same layer or every time the button is pressed a new layer appears?

add annotations functionality*

**Comment by idanbarak** [comment]
@carmelorr

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/29611813-b86695a0-8807-11e7-8d2d-059eb6d7f86e.png)

**Comment by carmelorr** [comment]
Tools menu-
![image](https://user-images.githubusercontent.com/26301386/29748784-ec1d2eec-8b25-11e7-9c94-72662fe1a0e1.png)

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/29749716-62f9d988-8b3b-11e7-8d50-b078c9bc6f03.png)

Annotation menu-
Double clicking the annotation will open the following window. this window will allow the user 2 things:
1. Reading state- the user will be able to see the data.
2. Editing state- by pressing the editing button the user will be able to edit the annotation shape (enlarge, minimize) stroke (weight,type) color (stroke and fill). in addition the user will be able to add tag-label to the annotation (the name value= label). The user will also be able to duplicate the annotation and delete it. 

The user will be able to "check" to save the annotation in time and/or save the annotation in the overlay. Saving in overlay means that when the overlay is open- the annotation will appear. Saving in time-TBD.

The user will be able to insert text In the description part (max 300 letters).

The creator, editor, layer and case should fill automatically.
At the moment- the case can be automatically, the layer= annotation layer, and the creator and editor can be filled manually. 

Show only the last version - all changes in shape and text will delete the previous version.

When duplicating the annotation- shape and data (text) will be copied- except the creator (which will be the copier) and editor.

**Comment by carmelorr** [comment]
The new ux definition is based on the current implementation:
* Tools menu includes: dot, line, poly line, circle, square and arrow. 
* Tools menu enable to user to change the colors, stroke and fill.
* All annotation are on the same layer.
* Annotation layer is part of the layer manger, and can be turned off.
* Annotation layer is shown on all screens, according to the zoom level.
* Delete annotation is be selecting the annotation and pressing right click.

**Comment by idanbarak** [comment]
@asafMasa @osadan 
The annotation dialog is still part of the requirement even tough we decided to not develop it for the current milestone

**Comment by carmelorr** [comment]
Please see bug #832
