### ISSUE TITLE
Bug - When you return to previous case the overlay doesn't load correctly  

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#281]
- [x] bug report => search github for a similar issue or PR before submitting
- [ ] feature request
- [ ] support request
- [ ] Task/UserStory

**Current behavior** 

When you select existing case that overlay was presented in one of the imagery views,
It doesn't show the overlay that was presented.

**Expected behavior** 

Show all the overlays that were selected in the imagery that they were presented.

**Minimal reproduction of the problem with instructions** 
1. select case
2. change the imagery outline to one of his outlines (2 or 3 or 4)
3. select overlay to present on each imagery view
4. close the browser open it again and select the case that you worked on.

**What is the motivation / use case for changing the behavior?** 

The user should return to the same state.

**Comment by osadan** [comment]
this is the same as #173 and will be resolved their
