### ISSUE TITLE
As a <Developer> , I want that <the "Area Analysis" will be defined> so that <I can know how the context should affect the application layout>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#310]
Define the "Area Analysis" Context 
Filtering params (Facets - Sensors), Display mode (num of screens, ...),Radius from geo coordinate, ..(refinement of Definition of Context params by Idan)
The context should define the initial setting of the map when being loaded (zoom, area, rotation, ...) from context
@idanbarak @carmelorr -  
### Should be defined in the first two days of the iteration

**Comment by carmelorr** [comment]
**Current view-**

when the user activates this context, the system will be at this state:

No. of screens= 1
Default overlay = latest (#312)
Zoom level= 18.5
Imagery count= 10
Time filter= (start- end) latest until the 10th overlay.
Geo filter= pin-point
Orientation= original
Facets= sensor type- only VIS; resolution- 50 cm1 px; TBD..

@idanbarak what do you think about the imagery count?

**Comment by ronenru** [comment]
@carmelorr please also define the prediction mode to be used for this context 
@eldadcohen1 @idanbarak

**Comment by carmelorr** [comment]
Prediction mode- movement over time.
In this context the user will analyze the same area with different overlays.

**Comment by idanbarak** [comment]
fixed location
temporal prediction
