### ISSUE TITLE
(bug) - Menu annotation buttons flickering at the edge of the screen

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#3169]
**Steps**
Draw an annotation and drag it to the edge of the window (Something like the picture) ,click on it to display the menu ,then wait a few seconds
![image](https://user-images.githubusercontent.com/46754845/81156920-1db94d80-8f8f-11ea-9bbe-257f32331e53.png)

* You may have to play around with it for a bit to make it happen

**It can really interfere with editing the annotation ,because it moves all the time**
![image](https://user-images.githubusercontent.com/46754845/81157416-9f10e000-8f8f-11ea-9f86-e7014595816e.png)
![image](https://user-images.githubusercontent.com/46754845/81157671-e26b4e80-8f8f-11ea-92cd-5c57859798db.png)

**Comment by ramtob** [comment]
@PiniAmiram 
It does jump a few times but it stops after a few jumps.
Is that what you meant?
Or you see it jumping continuously? This I didn't see.

**Comment by PiniAmiram** [comment]
@ramtob I see it all the time it doesn't stop
