### ISSUE TITLE
(bug) - Unknown images - The table shows another name

### ISSUE THREAD

**Issue by PiniAmiram** [AnSyn/ansyn#3181]
![image.png](https://images.zenhubusercontent.com/5c46ec3ab0c6b33edb491848/6d968481-71de-46f7-bc8c-891f972c6d65)

Share link: 
http://platform.ansyn.io:81//#/?facets=(filters:!((fieldName:sensorName,metadata:(disabledEnums:!(),unCheckedEnums:!('Multi-Spectral Instrument',Video)),type:Enum),(fieldName:isGeoRegistered,metadata:(disabledEnums:!(),unCheckedEnums:!()),type:Enum)),showOnlyFavorites:!f)&time=(from:'2019-07-23T09:24:34.000Z',to:'2020-05-07T09:24:34.358Z',type:absolute)&maps=(activeMapId:af3b94d2-03ff-44e6-9f73-10d386aff493,data:!((data:(imageManualProcessArgs:(Brightness:0,Contrast:0,Gamma:100,Saturation:100,Sharpness:0),isAutoImageProcessingActive:!f,overlay:!n,position:(extentPolygon:(coordinates:!(!(!(-122.40535327877414,37.63841420145354),!(-122.34343979107203,37.63841420145354),!(-122.34343979107203,37.6113738005987),!(-122.40535327877414,37.6113738005987),!(-122.40535327877414,37.63841420145354))),type:Polygon),projectedState:(center:!(-13622657.226970552,4526568.889831425),projection:(code:'EPSG:3857'),resolution:4.9229842315974395,rotation:0,zoom:14.956666666666665))),flags:(),id:af3b94d2-03ff-44e6-9f73-10d386aff493,orientation:'Imagery Perspective',worldView:(mapType:openLayersMap,sourceType:BingWithLabel))),layout:layout1)&region=POLYGON ((-122.39522600114287 37.621532617636205, -122.3914227440412 37.6227585878962, -122.38487760391266 37.61908061646335, -122.39213032675775 37.61606804717195, -122.3958009121001 37.617854585551015, -122.39522600114287 37.621532617636205))&overlaysManualProcessArgs=()&layers=!(ac9fca5a-b365-f015-c6db-f0713a804e51)&miscOverlays=()

**Comment by tltk90** [comment]
@PiniAmiram @Talschneidy it is a bug??
is because in the filter we show the sensor name, and in the table we show the sensor type

**Comment by PiniAmiram** [comment]
@tltk90 Okay I didn't know that

**Comment by tltk90** [comment]
@Talschneidy what you say, it is a bug or we can close it?
