### ISSUE TITLE
Launch in Context info entity - As a <Developer> , I want that <the "Launch in Context info entity" will be defined> so that <I can know how the context should affect the application layout>

### ISSUE THREAD

**Issue by ronenru** [AnSyn/ansyn#329]
Define the "Lunch in Context info entity" Context 
Filtering params (Facets - Sensors), Display mode (num of screens, ...),Radius from geo coordinate, ..(refinement of Definition of Context params by Idan)
The context should define the initial setting of the map when being loaded (zoom, area, rotation, ...) from context
@idanbarak @carmelorr -  
### Should be defined in the first two days of the iteration

**Comment by carmelorr** [comment]
Launch in context info entity-

when the user activates this context, the system will be at this state:

No. of screens= 2 (side by side) 
Default overlay = closest in time before and after.
Zoom level= 18.5
Imagery count= 30 before and after, 60 in total. 
Time filter= type-start/end. -> end: utc_now start:?
Geo filter= pin-point
Orientation= original
Facets= sensor type- VIS only; resolution- 50 cm1 px; TBD..
Prediction mode- temporal prediction
Data layers- the entity layer should be brought to the case and be presented on the overlays. 
The time-line needs to show the entity time.

**Comment by idanbarak** [comment]
@MarkShleifer 
at the moment there is no need to import a data layer from a service. the url will include the coordinates of the entity and its geometry in WKT format.

**Comment by carmelorr** [comment]
Please see bug  #912
