### ISSUE TITLE
Design bug- shadow mouse

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#336]
Please see the correct icon-
https://www.figma.com/file/OpHMLQ4eNnYWlv1lM0A2793w/Colombus-draft?node-id=206%3A6047

background: #FFFFFF;

Active + focused = 100%
Active + unfocused= 70%
Inactive= 50%

**Comment by idanbarak** [comment]
@carmelorr

**Comment by carmelorr** [comment]
@idanbarak 
It is not possible to attach SVG here. I send it to developers via slack.

![image](https://user-images.githubusercontent.com/26301386/28363674-119bad5c-6c8a-11e7-846b-7de34bd21f3b.png)

**Comment by eldadcohen1** [comment]
Close ( Duplicate )
