### ISSUE TITLE
right click on annotation will open manage menu

### ISSUE THREAD

**Issue by ronenru** [AnSyn/ansyn#342]
By right clicking on an annotation a manage menu will open it will let the user to edit the metadata of the annotation and also to delete and duplicate the annotation.
part of #273

**Comment by asafMasa** [comment]
see https://github.com/AnSyn/ansyn/issues/818
#818

**Comment by asafMasa** [comment]
@carmelorr @idanbarak what is the status of this issue? can we close it?

**Comment by idanbarak** [comment]
no, we will develop it in the future

**Comment by asafMasa** [comment]
Duplication of #818 i'm closing it
