### ISSUE TITLE
Define range of user monitor (screen) resolution

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#375]
max - 1920X1200
min - 1024X768

**Comment by eldadcohen1** [comment]
Please define all the range of resolutions . @idanbarak @carmelorr

**Comment by carmelorr** [comment]
@idanbarak @eldadcohen1 
1920x1080
1366x768
1280x1024
1280x800
1024x768

**Comment by idanbarak** [comment]
chrome extension:
https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh?hl=en

**Comment by AmitMY** [comment]
Can I get a little more to go with?
I am assuming that what you are asking here is compatibility down to 1024x768, but I don't know what is incompatible.
I can see that the status bar needs adjusting, but is there anything else?

+Checked on an iPad, just want to get a clarification: Are we targeting any touch device? If so, we'll need some changes to interactions

**Comment by idanbarak** [comment]
@AmitMY 
no need for touch device compatibility at the moment

incompatibility is a state where the user cannot access one of the app's controllers or view indications

for example, in the image attached to your post the user cannot view the overlays indication

**Comment by AmitMY** [comment]
Yeah, I meant are there any more cases you are aware of that are incompatible? This was the only one I found

**Comment by asafMasa** [comment]
@idanbarak @carmelorr test resolutions

**Comment by carmelorr** [comment]
@idanbarak it looks good. didn't find any incompatibility.
