### ISSUE TITLE
As a <User>, I want to <*momentarily* sync zoom level, position and orientation between imageries views> so that <I can analyzed the area in the same orientation>  

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#381]
Synchronization will be just when the button clicked. All the imageries will be in the same orientation of the clicked imagery .

- [ ] Implement the logic to sync imageries according to one imagery.
- [ ] Add all the ui button and logic that necessary according to the design of @carmelorr and @idanbarak.
- [ ] Implement for customer app and for the public app.

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28245125-061b09fc-6a08-11e7-9e1e-70a6ffdb35c2.png)
https://www.figma.com/file/B5NhopxxBLfZ68by5L6ERR1E/Colombus-june-2017-Main?node-id=0%3A1705
![image](https://user-images.githubusercontent.com/26301386/28245129-1f23099a-6a08-11e7-92d9-df482493c0b2.png)
https://www.figma.com/file/B5NhopxxBLfZ68by5L6ERR1E/Colombus-june-2017-Main?node-id=0%3A1300

**Comment by carmelorr** [comment]
Sync imagery views:

The connection between imagery views is set by pressing the "link button" (one click for continuous connection and double click for temporal connection). Both connections will be according to the connectivity settings.

The connectivity settings are set by the "link button" in the status bar, and will include:

Orientation, location and zoom level according to the active screen.

Absolute zoom level- all imagery views will be in the same zoom level.
Relative zoom level- all imagery views will maintain their relative zoom level.

**Comment by carmelorr** [comment]
@idanbarak

**Comment by carmelorr** [comment]
Update-
At this moment we can do a basic format-
only a momentary connection is needed, with all screens connected and all capabilities (location, orientation and zoom level- absolute)

**Comment by idanbarak** [comment]
@carmelorr 
please create new issue regarding permanent sync between different imageries

**Comment by carmelorr** [comment]
@idanbarak please see new permanent issue #268

**Comment by carmelorr** [comment]
@idanbarak 
What do you think of the icons- the first is for momentary and the one with the lock is for permanent?
![image](https://user-images.githubusercontent.com/26301386/28372168-9ff535b0-6ca7-11e7-92be-c1ff6685f732.png)

**Comment by idanbarak** [comment]
@carmelorr 
I think it that when seen in standard resolution, it is going to too be hard to distinguish between the icons

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28674677-c91ef302-72ee-11e7-9000-fd035c5484ca.png)
@idanbarak  better?

**Comment by idanbarak** [comment]
@carmelorr 
better, thanks!
