### ISSUE TITLE
Define "Embedded" app configuration

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#383]

**Comment by carmelorr** [comment]
Embedded app will include:
Imagery screens
Timeline
Status bar
Option to open full app
Image processing tools
Context menu

When activating the embedded app- a temporary case will be created, and will enable to switch easily to the full app mode.

**Comment by idanbarak** [comment]
@carmelorr 
please add wireframes example

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/28621019-300f7118-7218-11e7-8f31-931350b5e8ec.png)

![image](https://user-images.githubusercontent.com/26301386/28621045-4226cf22-7218-11e7-85d4-ad49553d91c6.png)

![image](https://user-images.githubusercontent.com/26301386/28621055-4e993952-7218-11e7-8e9c-8ec552314951.png)

![image](https://user-images.githubusercontent.com/26301386/28621075-61608356-7218-11e7-90a6-b3d90a00719e.png)

![image](https://user-images.githubusercontent.com/26301386/28621088-733c8cbe-7218-11e7-8458-f48f2183b9d2.png)

**Comment by carmelorr** [comment]
Another functionality options-

![image](https://user-images.githubusercontent.com/26301386/29073637-06a2a4c0-7c55-11e7-888b-ebfe9cf887ae.png)

Or

![image](https://user-images.githubusercontent.com/26301386/29073651-17387bde-7c55-11e7-993c-67baf2902306.png)

**Comment by carmelorr** [comment]
As decided today- the "embedded" app configuration formats are-

1. one/ four screens view
2. screen/ screens with time line
3, screen/screens with tolls bar
4. screen/screens with time line and tool bar

**Comment by idanbarak** [comment]
just to be clear 
is the one that appears in @OmKoren  document
