### ISSUE TITLE
Add north arrow indicator

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#416]
@carmelorr 
please add design (svg file)
and basic interactions

**Comment by carmelorr** [comment]
The north arrow will appear in the upper right corner of the screen and will indicate the direction of the presented imagery (it will change according to the image rotation). Pressing the icon will change the rotation of the image to face north (north in 0 deg.). Pressing the icon again will rotate the image to its original direction (filming position). Same will apply for numerous screens. The north arrow will appear and apply for all layout types (in world view pressing the icon will only rotate to facing north position).

Please see attached  
https://www.figma.com/file/YznWGJI3BKJ5IFQZc37G2u4U/columbus-for-figma-Page-1?node-id=57%3A0



![image](https://user-images.githubusercontent.com/26301386/28564202-f4a8790e-7130-11e7-9f88-e4fddb6e7adb.png)

![image](https://user-images.githubusercontent.com/26301386/28564254-1584486a-7131-11e7-8243-ed7d244be3f3.png)

**Comment by idanbarak** [comment]
Z-index: arrow should appear above the header

**Comment by carmelorr** [comment]
When the screen is inactive the north arrow will be in black and white, as mentioned in #418 

Also, as decided today in the sprint meeting- the implementation of the north arrow will be according to "open layers".

**Comment by idanbarak** [comment]
we have decided that we are going to use the native OL4 north indication
