### ISSUE TITLE
indication to an imagery window that contains an overlay who is not part of the case

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#417]
- [x] Add flag 'overlayNotFromCase' on status bar reducer.
 - [x] Add Map object 'NotFromCaseOverlays' on status imagery.
 - [x] UI 
 - [x] Tests

**Comment by carmelorr** [comment]
The indication will apply for an active screen and inactive screen. 
 please see attached-
![image](https://user-images.githubusercontent.com/26301386/28625515-290c7a20-7225-11e7-9fc2-696720d70e11.png)
![image](https://user-images.githubusercontent.com/26301386/28625542-3fbf4856-7225-11e7-81de-c1d7d2a9c2f3.png)

**Comment by idanbarak** [comment]
@carmelorr 
change image to "overlay"

**Comment by carmelorr** [comment]
@idanbarak ok

**Comment by carmelorr** [comment]
@idanbarak needs to say its ok
![image](https://user-images.githubusercontent.com/26301386/30056461-7abd0c78-923b-11e7-894d-b2a8ff18a9bf.png)

**Comment by idanbarak** [comment]
@carmelorr 
the image you provided is too small - unreadable. please provide a better image (i tried to find the design in figma, buy couldn't find it..)
