### ISSUE TITLE
Bug: No notification to the user when overlay request ended with no results

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#424]
* Reproduce:
1. Pin point a location with no overlays 
2. No notification to the user appears and no points in the timeline

* Expected:
1. Message that search ended with no results 

* Actual:
1. No notification to the user
2. At **customer site** 404 error is thrown when no overlay is to be found

**Comment by carmelorr** [comment]
Please see #581

**Comment by idanbarak** [comment]
@eldadcohen1 can we implement in current iteration?

**Comment by eldadcohen1** [comment]
Close by #581
