### ISSUE TITLE
Bug: Histogram equalization algorithm is too coarse in colorful images

### ISSUE THREAD

**Issue by MarkShleifer** [AnSyn/ansyn#430]
- Reproduce:

1. Open a colorful overlay
2. Turn histogram on

- Expected:
Histogram button should improve the image appearance 

- Actual:
In some areas of the image, the algorithm is too coarse and making the image look burned

**Comment by eldadcohen1** [comment]
Not Relevant issue.
We will create new issue when we have a new algorithm.
