### ISSUE TITLE
Visualizer - As a <User> I want to <see the time and area info entity on the imagery> so that <I can understand the entity relationship with the presented overlay>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#435]
- [ ] Implement the visualizer according to @idanbarak @carmelorr definitions
 - [ ] show the time difference between the  entity and the presented overlay.

**Comment by carmelorr** [comment]
Entity will be presented on the overlay according to its type (icon) and Geo location. 
In addition, the entity time of creation or the last time it was edited- will be deducted from the overlay time, and presented underneath. The time form will be (-) dd:hh:mm.   

Please see-
![image](https://user-images.githubusercontent.com/26301386/28861288-dcbae816-7768-11e7-8f40-a8196c5aa2bb.png)

**Comment by idanbarak** [comment]
@carmelorr

**Comment by carmelorr** [comment]
@idanbarak  is this one ok?
Please see the map marker- 
https://biks.slack.com/files/carmel/F6L82H858/frame_35.svg

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/29249650-78bd6a46-803c-11e7-992b-633d97a19496.png)

**Comment by idanbarak** [comment]
entity input to the url will be in WKT format.

in case of a simple geometry (POINT) - show map marker

in case of a complex geometry (POLYLINE, POLYGON, etc..) - Show map marker in the middle of shape and draw the geometry.

**Comment by carmelorr** [comment]
@idanbarak @eldadcohen1 

Update- 
1.The polygon around the marker should be in the same color as the icon (#3DCC33)
2. The entity time should be calculated as following: 
Less then 24 hours= hours:minutes: seconds
After more then 24 hours= it will be in days: hours: minutes
After more then 30 days= it will be in months:days:hours
After more then  12 month= it will be in years:months:days.

Also, please add titles to the numbers "days", "years", etc.
