### ISSUE TITLE
As a <User> I want to see <external event on the timeline> so that <I can analized which overlays are relevant >

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#436]
- [x] Implement according to @idanbarak  and @carmelorr  definitions.
- [x] Add the functionality to event drops
- [x] Create relevant effects and reducers 
- [ ] unitests

**Comment by carmelorr** [comment]
External event will appear on the time line in this form-
![image](https://user-images.githubusercontent.com/26301386/28861737-d4fd36ae-776a-11e7-8127-19448d0a5d8d.png)

Pressing the icon will present the "info entity" that's attached to the event (present or emphasis-enlarge). In addition, when the "info entity" that's attached to the event is pressed- the icon on the time line will be marked (larger).  
If there are numerous events on the time line- the behavior will be the same as the overlay markers.
