### ISSUE TITLE
Logo and version info.

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#448]
Add system logo -  version info in a tool-tip that will open by hovering the logo

**Comment by idanbarak** [comment]
use the following temporary icon
![screen shot 2017-07-31 at 18 21 15](https://user-images.githubusercontent.com/4181572/28784824-3019c5e2-761d-11e7-8850-4f9463a7a59a.png)

**Comment by idanbarak** [comment]
i cannot upload svg's here - the developer who get this task can contact me and ill send the file directly
