### ISSUE TITLE
Design bug- tools buttons

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#455]
Please check the design and implementation of the buttons.

**Comment by carmelorr** [comment]
Please see design-

Available buttons: Background= #FFFFFF opacity 25%, Icon= #FFFFFF opacity 80%
active (selected) buttons:  Background= #FFFFFF opacity 25%, Icon= #FFFFFF opacity 100%

**Comment by idanbarak** [comment]
@carmelorr 
please attach an image..thanks

**Comment by carmelorr** [comment]
@idanbarak  please see attached-

![image](https://user-images.githubusercontent.com/26301386/29124733-64448404-7d22-11e7-99a1-fa9346191365.png)

**Comment by AmitMY** [comment]
And how do you want disabled to look like?

**Comment by idanbarak** [comment]
@AmitMY 
disabled button design is already implemented
