### ISSUE TITLE
Design bug- resolution

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#459]
In 1366X768 resolution- can't see the imagery amount.

![image](https://user-images.githubusercontent.com/26301386/28811453-ee144a8e-7697-11e7-96ef-83a478e155e1.png)

**Comment by carmelorr** [comment]
Also, when changing to two and more screens- can't see even the icon.
![image](https://user-images.githubusercontent.com/26301386/28838692-ca0b65ca-76f9-11e7-93dc-4d426a78dd67.png)

**Comment by eldadcohen1** [comment]
Duplicate will be handled in #375
