### ISSUE TITLE
As a <user>, I want to <able to launch the application in "Launch in Context of Info Entity" context > so that <I can analyze the area according to the info entity> 

### ISSUE THREAD

**Issue by ronenru** [AnSyn/ansyn#465]
Allow launching the app by providing a URL with the wanted context and AOI as URL params.

- [ ] update the case state according to the definition of this context by @idanbarak @carmelorr - #329 
- [ ] write all the necessary action and events to notify the app about the launched context.
- [ ] **As part of the implementation provides a readme file that describe the different params supported in the URL**

**Comment by carmelorr** [comment]
Please see bug  #912
