### ISSUE TITLE
Overlay heat-map and polygons

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#471]
Full functionality
Icon in tools bar

**Comment by carmelorr** [comment]
overlay foot prints (polygons and heat-map) functionality-

This functionality is available for all overlay types (world view and sensors) 

One click on the designated button will show the overlay polygons only on the active screen. 
Hover this button will open a menu with another button for the heat map (aggregated data)- one click on this button will show the heat map only on the active screen.

closing them will be by clicking the buttons again (@idanbarak and by the layer management?)

There is not an option to show both overlay polygons and heat map on the same screen. 
For example- if the heat map is open on one screen and the user opens the overlay polygons on the same one- the heat map will close. 

The user will be able to open on one screen the heat map and on the others the polygons (or nothing at all). 

This functionality does not need to be saved as part of the case. How ever it is part of the URL. 

Please see-

![image](https://user-images.githubusercontent.com/26301386/29062442-63cfb6b8-7c2a-11e7-8874-8cec6f8c64ec.png)

![image](https://user-images.githubusercontent.com/26301386/29062423-5916e908-7c2a-11e7-91a6-a5647dec1f76.png)

![image](https://user-images.githubusercontent.com/26301386/29062454-77d01efa-7c2a-11e7-9c75-08a42c364ed1.png)

![image](https://user-images.githubusercontent.com/26301386/29062477-8a6d6202-7c2a-11e7-9295-ae6b1681d072.png)

![image](https://user-images.githubusercontent.com/26301386/29062580-e504ac84-7c2a-11e7-84c4-019450e0e6f1.png)

@idanbarak in an inactive screen- layers and tools (annotations, measurements, footprints, etc.) should be in black&white?  

@idanbarak asaf had an idea to open the polygons in clusters, what do you think?

**Comment by idanbarak** [comment]
![3](https://user-images.githubusercontent.com/4181572/29070776-60894b94-7c49-11e7-8b0f-d5798e7cf6f1.jpg)
![2](https://user-images.githubusercontent.com/4181572/29070777-60ac4cac-7c49-11e7-9376-1060251b9df0.jpg)
![1](https://user-images.githubusercontent.com/4181572/29070778-60b7751e-7c49-11e7-9487-43552df9f33b.jpg)

**Comment by carmelorr** [comment]
Update-

@asafMasa  according to our talk, please see-

![image](https://user-images.githubusercontent.com/26301386/29072778-d7026f96-7c51-11e7-9a64-4366f02149cd.png)

Also, please see- Interaction and functionality of the visualizers #473

**Comment by idanbarak** [comment]
looks good
