### ISSUE TITLE
Visualizers - As a <User> I want to <see the object that was gave in the context on the imagery> so that <I will stay in the context of the object on the imagery>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#478]
- [x] Create Visualizer for info entity @idanbarak @carmelorr How the info entity on the imagery should looks like?
- [x] Show the Info entity on the imagery
- [x] Unittests

**Comment by carmelorr** [comment]
Please see How the info entity on the imagery should looks like in #435
