### ISSUE TITLE
Log-in and Landing page - As a <User adminitrator> I want that <just the allowed user will log-in the app> so that <our site will be just for our uses>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#479]
- [x] Create Login state #534 
- [x] Create Login page ( ui )
- [x] Custom the backend according the new functionality
- [x] Integrate the landing page according to @carmelorr desing

**Comment by carmelorr** [comment]
@idanbarak  what do you think?

![image](https://user-images.githubusercontent.com/26301386/29493275-b010bb74-859b-11e7-9b16-afc7234e07ab.png)

**Comment by carmelorr** [comment]
@idanbarak  what do you think?

![image](https://user-images.githubusercontent.com/26301386/29495785-a966dc3a-85ce-11e7-9317-4361c91ed580.png)

**Comment by idanbarak** [comment]
looks nice

**Comment by idanbarak** [comment]
@eldadcohen1 
login page is done, lets move the landing page assignment to the next iteration
