### ISSUE TITLE
Change icons from SVG to Font

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#489]
As decided in the sprint meeting today,  all new icons should be in Font format.

**Comment by carmelorr** [comment]
[icomoon (4) (1).zip](https://github.com/AnSyn/ansyn/files/1255232/icomoon.4.1.zip)

**Comment by idanbarak** [comment]
@carmelorr

**Comment by carmelorr** [comment]
With the new name-
[AnSyn.zip](https://github.com/AnSyn/ansyn/files/1290520/AnSyn.zip)

**Comment by AmitMY** [comment]
Dependent of https://github.com/AnSyn/ansyn/issues/711

**Comment by carmelorr** [comment]
Please see #711
