### ISSUE TITLE
Upadate visualizers to get styles as in stylesheet

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#500]
'EntitiesVisualizer' will be responsible for 90% of the drawed entities.

Style Hierarchy:
1. Style set by object Id
2. Style set by stylesheet for entity type
3. Style set by stylesheet default style
4. Default Hard coded style

Stylesheet example: 
```
  const styleSheet = {
  defaultStroke: 'blue',
  default fill: 'transparent'
  entitiiesStyle:  [
  { type: 'Polygon',
    stroke: 'blue',
    strokeHover: 'green',
    fill: 'white',
    fillHover: 'red'} ,
   { type: 'Car',
    icon: "/assets/car.svg"},
    etc.]}
imageryProviderService.registerVisualizer("openlayers", EntitiesVisualizer, styleSheet);
```
styleSheet=> will determine each entity style by its type and can be provided by designer from outside
                      it will replace app theme withaout having to open the code

2. if type to draw is not in stylesheet go to default stylesheet color
3. add option to set entityId's style in run time (and to clear such style)

**Comment by AmitMY** [comment]
@asafMasa Where will we set the visualizer type? for example, `type: 'Car'`
