### ISSUE TITLE
Define Overlay-Frame Transition

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#507]
Define how the user move from Overlay presentation to single frame presentation.

**Comment by carmelorr** [comment]
Overlay- frame transition has 3 levels:
1. System level: all frames will be regarded as overlays, for all functionalities. 
2. Overlay level:  includes the frames of a certain overlay.  This mode will apply only the active screen.
3. Specific location level: includes the frames of a specific location in an overlay. This mode will also apply only the active screen. 

**System level**
*A designated check box will be added to the filters menu-"enable frame mode".
*Frames will be regarded the same as overlays in this mode- including the time line, status bar, filters, layers and tools menu. (design- timeline, footprint, heat-map, favorites)
* The back button (on the screen menu), will include the "back to overlay" option, meaning the users will be able to transfer from a frame to an overlay and from an overlay to the base map. 

**Overlay level**
*A designated button will be added to the screen menu-"show frames layout/ footprints". double clicking the polygon will open the frame (on the same screen). 
* The back button will enable the user to return to the overlay (and from the overlay to the base map).
* The frame date and time will be written on the headline. 
*The frame will not be a part of the time line. 
* The frame can be part of the favorites (and then it will be a part of the time line and the favorites list). 

**Specific location level**
*Pressing a designated button in the context menu will enable the user to see the frames that assemble a certain point of the overlay. (design- By clicking the footprint or by pre-view?) 
* The back button will enable the user to return to the overlay (and from the overlay to the base map).
* The frame date and time will be written on the headline. 
*The frame will not be a part of the time line. 
* The frame can be part of the favorites (and then it will be a part of the time line and the favorites list).

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/31725317-b281d57c-b42c-11e7-8b58-f47d8a092158.png)
