### ISSUE TITLE
Design and define overlay preview/de-clutter (from timeline)

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#510]
Tasks:
- [x] Show empty floating window for single hovered overlay
- [x] Investigate how to get planet thumbnail and if it supports png/jpeg for specific polygon
- [x] Show thumbnail for 1 overlay -> pull request
- [ ] Show thumbnail for N overlay over the same position -> pull request

**Comment by carmelorr** [comment]
![2 15](https://user-images.githubusercontent.com/26301386/38244095-368284f0-3742-11e8-9e27-42bc8e7f9b12.png)
![2 16](https://user-images.githubusercontent.com/26301386/38244096-3755df9e-3742-11e8-8a76-2b413cb1a42f.png)

**Comment by carmelorr** [comment]
overlay preview-
the user will be able to hover the overlays in the timeline and get a preview of each overlay.
if the user will hover an aggregate overlays- then a numerous preview windows will open. double click the preview window will open the overlay.

**Comment by idanbarak** [comment]
@carmelorr 
1. what is the preview? a thumbnail of the entire overlay? or just the overlay cropped to the active map extent? 
2. please explain more about the red indication on the timeline in the aggregate overlays situation.

**Comment by carmelorr** [comment]
The preview for start can be a thumbnail of the entire overlay (basic form), but the idea is that the preview will be the overlay cropped to the active map extent. 

The red indication on the timeline shows the aggregated overlays- in case at a certain time there is more than one overlay, a numerous preview windows will open. 1-10 will be as the image above. if there is more than 10 the user will get an indication (and will be asked to zoom in or TBD  )

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/38309548-053b0138-3823-11e8-8ebc-f3f0e74c47a3.png)
