### ISSUE TITLE
visualization of entity on the map

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#512]
An entity will appear on the map when the layers presentation will be on (new functionality- see image).

The layer management will show which layers are active and inactive (including entities layers)- for all screens. 

And for each screen the user will be able to choose to show or hide all of them(toggle).

Inactive- opacity= 70%

![image](https://user-images.githubusercontent.com/26301386/29568032-c2495e3c-8757-11e7-8c81-27c22ef10f8e.png)

Active- opacity= 100%
 
![image](https://user-images.githubusercontent.com/26301386/29567988-97f968c0-8757-11e7-9506-61adcfd290b0.png)

**Comment by asafMasa** [comment]
@carmelorr @idanbarak is this issue still relevant?
What entities layer are we talking about? annotations?

**Comment by carmelorr** [comment]
@asafMasa the show/hide layers button will apply all the relevant layers (as set on the "layers manager").

Entities layer include annotations, data layers and "launch in context of info entity".
