### ISSUE TITLE
Design bug- context menu

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#527]
The secondary menu is unreadable.  

The menu should include the overlay type as opposed to name.

I labeled it ready for discussion.

**Comment by asafMasa** [comment]
@carmelorr @idanbarak now it is 10px is 11px ok?

**Comment by idanbarak** [comment]
i dont think it will solve the problem, because you wont be able to fit enough text

me and @carmelorr will figure out a better solution

**Comment by carmelorr** [comment]
Update-
For the customer site, at the moment, please leave it as it is know.
For the rest-
Please set the following titles: Panchromatic= P, 4-band= 4B, 8-band= 8B
see attached-
![image](https://user-images.githubusercontent.com/26301386/32840711-27114d28-ca21-11e7-8b2b-b4b165858174.png)
