### ISSUE TITLE
Annotation in layer management 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#532]
Regarding issues #341 and  #273 

At the moment all annotations will be in the same layer, saved per case. 
The annotations will be saved automatically in that layer, in the same hierarchy. 
The layer will be saved and updated automatically after any change (and upon "save changes" request after editing an annotation).  

**Layer management**
The user will be able to show/hide the layer in the layer management. 
If the layer is shown in the layer management (checked)  it will be presented on all the screen. 
In case the user will wish to hide the layer in one of the screens- a designated button will allow it- see attached.

![image](https://user-images.githubusercontent.com/26301386/29814106-dcaddbce-8cb4-11e7-9514-0736c3006e8e.png)

layers on, opacity= 100%
![image](https://user-images.githubusercontent.com/26301386/29813434-bd396ed6-8cb2-11e7-8d7d-aa5421247450.png) 

layers off, opacity= 70%
![image](https://user-images.githubusercontent.com/26301386/29813450-c86fd5a6-8cb2-11e7-81e6-24e4fd953ed8.png)

**Comment by asafMasa** [comment]
related to #538

**Comment by carmelorr** [comment]
Please see bug #832

**Comment by carmelorr** [comment]
Please see bug #900 still can't hide layers from imagery screen.
