### ISSUE TITLE
Data layers

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#533]
As discussed, 8 layers should be as a service from Open-street map.  
- [x] generate 1 checkbox by *ngFor
- [x] fetch layer data (same as case)
- [x] insert 1 layer to service and see the checkbox generated on startup
- [x] save layer data 'id' and checked state in case
- [x] on app refresh fetch layers from service and check by case data

**Comment by idanbarak** [comment]
@carmelorr 
in iteration 18 we need to reach an agreement with the client regarding the relevant data layers and find them online (probably OSM)

**Comment by carmelorr** [comment]
@idanbarak what about these:
http://wiki.openstreetmap.org/wiki/Tile_servers
http://wiki.openstreetmap.org/wiki/Featured_tile_layers
http://docs.openlayers.org/library/layers.html#vector

**Comment by idanbarak** [comment]
@carmelorr 
looks like a good source, but please create a more specific list of relevant layers
here's one for example: 
transport overlay  - http://wiki.openstreetmap.org/wiki/Openptmap

**Comment by carmelorr** [comment]
•	Transport overlay-  http://wiki.openstreetmap.org/wiki/Openptmap
•	Sea map- http://wiki.openstreetmap.org/wiki/OpenSeaMap
•	Hiking trails (mainly Europe)- http://hiking.waymarkedtrails.org/
•	Mountain-biking- http://mtb.waymarkedtrails.org/
•	Railway map (infrastructure, max speeds and signaling)-
 http://wiki.openstreetmap.org/wiki/OpenRailwayMap

**Comment by asafMasa** [comment]
@carmelorr please make sure that the recieved data is wkt or geoJson
