### ISSUE TITLE
Design bug- no. of screens

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#548]
When changing the layout to one screen (from 2/3/4 screens)- the system does not enlarge the active screen (only the top left one).
In addition- when changing back from one screen to 2/3/4 screens- the previous overlays are close, and only the world view is open. 

@idanbarak  

When the users wish to **momentarily** enlarge one of the screens-how can they do that? 
Add a designated button and/or functionality (double click the header?) or by changing to one screen?

**Comment by idanbarak** [comment]
@carmelorr 
not a bug..
we discussed in person. need to define layout change behavior

**Comment by carmelorr** [comment]
Layout behavior-
1. When changing the layout to one screen (from 2/3/4 screens)- the system needs to enlarge the active screen.
2. When changing the layout to fewer screens (for example from 4 to 3/2/1)- the system should save the latest overlay presented (on the other screens), so the user will be able to change back.  
3. Other scenarios for presentation: (add table @carmelorr)

**Comment by idanbarak** [comment]
final decision:
1. when increasing number of imagery windows - new ones appear as base maps (current behavior)
2. when decreasing - active window always remains active and presented
