### ISSUE TITLE
Design bug

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#550]
Decide how hovered, selected, active and inactive buttons looks like? 

(light blue frame/ dark background/ etc.)

**Comment by carmelorr** [comment]
@idanbarak  what do you think?

**First option:**

Tools menu-
*Normal*- background= #FFFFFF , 25% +  icon= #FFFFFF , 100%
*Hove*r- background= #000000, 25% +  icon= #FFFFFF , 100% 
*Pressed*- background= #000000, 25% +  icon= #FFFFFF , 100% 
*Disabled*- background= #FFFFFF , 25%  +  icon= #FFFFFF , 30%

See attached:

![image](https://user-images.githubusercontent.com/26301386/30272835-01ca2b98-96ff-11e7-987e-e086121ecea2.png)

**Second option:**

Tools menu-
*Normal*- background= #FFFFFF , 25% +  icon= #FFFFFF , 100%
*Hove*r- background= #EBF8FA, 100% +  icon= #156879, 100% 
*Pressed*- background= #EBF8FA, 100% +  icon= #156879, 100% 
*Disabled*- background= #FFFFFF , 25%  +  icon= #FFFFFF , 30%

See attached:
![image](https://user-images.githubusercontent.com/26301386/30273070-0b3123de-9700-11e7-942d-c970ae63eadb.png)

**Comment by idanbarak** [comment]
second option is better
still need to add a distinct hover design

@eldadcohen1 i remember you said you want to fix this a soon as possible..

**Comment by idanbarak** [comment]
never mind, already implemented
