### ISSUE TITLE
Design bug- pin point and context menu

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#551]
When opening the context menu in a cretin location, the Geo filter (pin point) will be the center of the context menu.

**Comment by idanbarak** [comment]
@carmelorr 
not detailed enough - you cant expect a developer to read this line and know what to do .please provide a detailed design.

**Comment by carmelorr** [comment]
Because the context menu acts as an overlay filter for a certain location, we wish to add the pin-point Geo filter as the center of the context menu.

Two levels:

1.Minimal changes to the current design: the center of the context menu will enable the user to set the pin point Geo filter for this location (the context menu location). After selecting to set the pin point- the functionality will be the same as setting the pin point from the status bar. In addition- you should consider the fact that this functionality should act in the future for polygon (edit existing polygon) and expected screen. 

See attached-
![image](https://user-images.githubusercontent.com/26301386/30249681-9b11f33c-9649-11e7-9da6-528b0a5ca9c6.png)

![image](https://user-images.githubusercontent.com/26301386/30249690-d95852e4-9649-11e7-9495-3b0925b836bc.png)

2. Change the current design- enlarge the center button of the context menu and add designated text. Same functionality as mention above. 

![image](https://user-images.githubusercontent.com/26301386/30249692-e63016f0-9649-11e7-9664-97b84807682b.png)
![image](https://user-images.githubusercontent.com/26301386/30249693-f37ce2a2-9649-11e7-820d-2e6b8e4b07f0.png)

**Comment by idanbarak** [comment]
@eldadcohen1 
at the moment only the minimal level is required.
