### ISSUE TITLE
Design bug- mark as favorite

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#552]
Move the "star button" that checks for favorites, to the screen status (as opposed to the current location on the status bar).

**Comment by carmelorr** [comment]
Please see-
![image](https://user-images.githubusercontent.com/26301386/30317994-809cdf8c-97b4-11e7-9d43-a01960bb3915.png)
![image](https://user-images.githubusercontent.com/26301386/30318395-aa185e94-97b5-11e7-9d9d-53c64d453414.png)

When the screen is not active the icon opacity will be 70% (#FFFFFF), no background. 
When the screen is active-
Normal= icon opacity 100% (#FFFFFF), no background.  
Hover= icon opacity 100% (#FFFFFF), background #000000, 87% .
Selected= icon opacity 100% (#FFFFFF) stroke (1px, #E6ECA0, 100%) , background #000000, 87% .
Disabled= icon opacity 30% (#FFFFFF), no background. 


![8 8](https://user-images.githubusercontent.com/26301386/30318006-89cd8f8e-97b4-11e7-83ce-240320c8b7b9.png)

**Comment by carmelorr** [comment]
See icons-
[Colombus - draft.zip](https://github.com/AnSyn/ansyn/files/1295546/Colombus.-.draft.zip)

**Comment by AmitMY** [comment]
@carmelorr I think this one is done, just need to remove it from the status bar, when the new status bar design is ready.
