### ISSUE TITLE
Design bug- world view

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#564]
Please set fixed zoom level (zoom out) for world view. there is no need to duplicate the globe. 
In addition, show only one globe (world view) when moving to the sides

**Comment by idanbarak** [comment]
<img width="1284" alt="screen shot 2017-09-18 at 10 42 18" src="https://user-images.githubusercontent.com/4181572/30532647-18b42200-9c5e-11e7-8de0-532f78b00bc6.png">

**Comment by idanbarak** [comment]
@eldadcohen1 
i have changed the issue from ׳design bug׳ to ׳bug׳

**Comment by osadan** [comment]
I set minZoom at the main view to be 2.5 the side working fine and the top /bottom is still showing black screen if I pen up or down to much
