### ISSUE TITLE
Design Bug- rotation

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#569]
The rotation functionality will be by clicking the middle button on the mouse and dragging.

**Comment by carmelorr** [comment]
@asafMasa @yuvalbl 
No need to do this rotation functionality. It will part of the north arrow #795

**Comment by asafMasa** [comment]
@carmelorr @idanbarak is this task relevant? i thought that you changed your mind about it?

**Comment by carmelorr** [comment]
@asafMasa please see the update on issue  #795 (rotation icon and tool tips for start)

**Comment by asafMasa** [comment]
@carmelorr ok i'm closing this issue as its obselete
