### ISSUE TITLE
Bug- URL

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#570]
The URL is too long and unusable
 See attached-
 
![image](https://user-images.githubusercontent.com/26301386/30247841-eb318442-9624-11e7-8862-e7f672938af6.png)

**Comment by idanbarak** [comment]
http://ansyn.io/#/?facets=(filters:!((fieldName:sensorType,metadata:!(GEOEYE01,WORLDVIEW02,WORLDVIEW03_VNIR,QUICKBIRD02)),(fieldName:sensorName,metadata:!('4-band (Blue, Green, Red, NIR) Multispectral','8-band (Coastal, Blue, Green, Yellow, Red, Red-edge, NIR1, NIR2) Multispectral'))),showOnlyFavorites:!f)&time=(from:'2000-09-07T12:22:00.000Z',to:'2017-09-14T12:22:28.485Z',type:absolute)&maps=(active_map_id:default_imagery1,data:!((data:(position:(boundingBox:!((coordinates:!(-124.04969388181757,40.721471300745634,0),type:Point),(coordinates:!(-124.04879538012263,40.72082463128288,0),type:Point)),center:(coordinates:!(-124.04924463097011,40.72114796679955),type:Point),rotation:6.287545840111019,zoom:21.046349772740815)),id:default_imagery1,mapType:openLayersMap),(data:(overlay:(id:'944f07f5-08c8-4d54-834a-1c74c364d968'),position:(boundingBox:!((coordinates:!(-124.18813713663386,40.80278852722739,0),type:Point),(coordinates:!(-124.15224503279518,40.78980122687477,0),type:Point)),center:(coordinates:!(-124.17019108471452,40.796295194642084),type:Point),rotation:6.287545840111019,zoom:15.7233718621985)),id:'192cbb2b-946e-19f7-eb92-142d46f57bb1',mapType:openLayersMap),(data:(overlay:(id:'928ab3a5-c6ed-412a-911c-3537e81fdbce'),position:(boundingBox:!((coordinates:!(-124.27734407029205,40.83639250757946,0),type:Point),(coordinates:!(-124.0130224490302,40.740738516991,0),type:Point)),center:(coordinates:!(-124.14518325966112,40.78858273566203),type:Point),rotation:6.287545840111019,zoom:12.842815816524983)),id:'821bbeb8-cfe8-ccea-ea2f-90e74b13ff2d',mapType:openLayersMap)),layouts_index:4)&region=POLYGON ((-124.16878574373894 40.798009477927366, -124.16866933793159 40.798005148748544, -124.16855405322096 40.797992202906116, -124.1684409999053 40.79797076508062, -124.16833126678989 40.79794104173813, -124.16822591069972 40.797903319141575, -124.16812594630031 40.797857960593475, -124.1680323363249 40.79780540293661, -124.1679459823019 40.79774615234638, -124.16786771587218 40.79768077945545, -124.1677982907798 40.79760991385763, -124.16773837561317 40.79753423804378, -124.16768854736675 40.79745448082853, -124.16764928588489 40.797371410330726, -124.1676209692421 40.7972858265756, -124.16760387010306 40.797198553789585, -124.1675981530984 40.797110432462304, -124.16760387324078 40.79702231125199, -124.16762097539696 40.79693503881241, -124.16764929482038 40.796849455619856, -124.16768855873941 40.79676638587915, -124.16773838898607 40.796686629586425, -124.16779830563894 40.79661095482508, -124.16786773164655 40.796540090369284, -124.1679459983853 40.796474718666026, -124.16803235209927 40.79641546926347, -124.16812596115945 40.79636291274862, -124.1682259240726 40.796317555253026, -124.16833127816258 40.79627983357899, -124.16844100884077 40.796250110993604, -124.16855405937581 40.79622867373068, -124.16866934106929 40.79621572823468, -124.16878574373894 40.79621139917283, -124.16890214640858 40.79621572823468, -124.16901742810207 40.79622867373068, -124.1691304786371 40.796250110993604, -124.16924020931529 40.79627983357899, -124.16934556340529 40.796317555253026, -124.16944552631843 40.79636291274862, -124.1695391353786 40.79641546926347, -124.16962548909257 40.796474718666026, -124.16970375583132 40.796540090369284, -124.16977318183893 40.79661095482508, -124.16983309849182 40.796686629586425, -124.16988292873846 40.79676638587915, -124.16992219265751 40.796849455619856, -124.16995051208093 40.79693503881241, -124.1699676142371 40.79702231125199, -124.16997333437948 40.797110432462304, -124.16996761737481 40.797198553789585, -124.16995051823578 40.7972858265756, -124.16992220159298 40.797371410330726, -124.16988294011112 40.79745448082853, -124.1698331118647 40.79753423804378, -124.16977319669807 40.79760991385763, -124.1697037716057 40.79768077945545, -124.16962550517597 40.79774615234638, -124.16953915115297 40.79780540293661, -124.16944554117757 40.797857960593475, -124.16934557677817 40.797903319141575, -124.16924022068798 40.79794104173813, -124.16913048757257 40.79797076508062, -124.16901743425693 40.797992202906116, -124.1689021495463 40.798005148748544, -124.16878574373894 40.798009477927366))

**Comment by idanbarak** [comment]
The polygon at the end of the url is too long - creates problems when trying to copy paste link.
please shorten to a 4-point polygon

**Comment by idanbarak** [comment]
@eldadcohen1

**Comment by osadan** [comment]
check if this was already resolved

**Comment by AmitMY** [comment]
@osadan Solved this, it is in production, now using only 5 points (4 points describing the area, 5th closing the polygon)
