### ISSUE TITLE
Bug- cases

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#573]
Number of bugs:

- [x] 1.Open existing case: loading time is very long (if at all), overlays are unavailable in the time line, sometimes the active and chosen overlays are not presented, status bar functions are inactive. 

- [ ] 2. Create new case- area analysis: status bar- can't mark favorites, Geo filter title does not show "pin point", orientation title does not show "original", after removing the favorite star- cant turn it on again. 

- [ ] 3. Save new case- after sharing this case, the number of available overlays is not the same (the filters  are not the same, for example Geoeye01 is selected, after it was checked off). Can't see active layers after sharing the case. 

- [x] 4. After opening existing case, can't change to another and /or the previous one. Also- the status bar functions are inactive, can't close the main menu (x), can't see overlays in the timeline, can't share link.

**Comment by eldadcohen1** [comment]
@carmelorr Please create an issue for each bug.

**Comment by carmelorr** [comment]
Please see:

#583 
#584
#585
#586
