### ISSUE TITLE
Bug: link sharing (facets) doesn't work properly

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#585]
Taken from #573 

- [x] 3. Save new case- after sharing this case, the number of available overlays is not the same (the filters  are not the same, for example Geoeye01 is selected, after it was checked off). Can't see active layers after sharing the case. 

Facets defined in link but doesn't affect the app

**Comment by osadan** [comment]
The problem is in default case after changing some filters and then sharing the link all filters are selected
