### ISSUE TITLE
Bug- time filter and time line

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#589]
Time frame in the timeline doesn't change according to the time filter. 

for example- see the time filter= 01.03.205-23.11.2016, time line= 12.09.2016-12.09.2017
![image](https://user-images.githubusercontent.com/26301386/30314659-0866dd92-97aa-11e7-9fbf-38f99a336b7b.png)

**Comment by carmelorr** [comment]
Sometimes it works-

![image](https://user-images.githubusercontent.com/26301386/30314905-ddc36bd6-97aa-11e7-9ce7-b7f2826302fd.png)

**Comment by osadan** [comment]
- [ ] add cursor to the ok

**Comment by osadan** [comment]
according to @carmelorr  this bug can not be reproduced order to some changes we made
