### ISSUE TITLE
Bug- opening a new overlay 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#590]
opening a new overlay cause an error (unable to do anything)- 

![image](https://user-images.githubusercontent.com/26301386/30315880-fe0037dc-97ad-11e7-9625-7ec69df9c07d.png)

Steps: 
open the system
select pin point (Boston)
change screen no. to 4 screens
select active window (bottom left)
click the latest overlay in the timeline (same occurs for the other overlays)
error

**Comment by carmelorr** [comment]
Same for another location and 3 screens

![image](https://user-images.githubusercontent.com/26301386/30316308-7cff48e2-97af-11e7-9b48-6b03c991352c.png)

**Comment by asafMasa** [comment]
This is a production bug (wrong configuration), the new version (that will be deployed today) should fix this.
