### ISSUE TITLE
Bug - On default case after search with new pin point, overlay is not presented

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#591]
**I'm submitting a ...**  

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
- Pin new point on the map (for example Miami)
- Request sent to the server for overlay request
- Results from the server are presented on the timeline
- Double click on drop (point/overlay) from the time line
- Overlay is not presented on the imagery
- System throws the following exception:
![image](https://user-images.githubusercontent.com/6008062/30317686-86466846-97b3-11e7-9a34-46299e412ab1.png)

**Expected behavior** 

- Display the selected overlay from the time line

**Minimal reproduction of the problem with instructions** 
As I mentioned on current behavior

**What is the motivation / use case for changing the behavior?** 

User should be able to see selected overlay

**Comment by osadan** [comment]
done!
