### ISSUE TITLE
Adding a case with context throws an error

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#592]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 

> ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'component' of null
> TypeError: Cannot read property 'component' of null

**Expected behavior** 
No error

**Minimal reproduction of the problem with instructions**
Go to: http://ansyn.io
Cases -> add case -> select context "tel aviv" -> check console

**Comment by asafMasa** [comment]
works fine on latest version
