### ISSUE TITLE
Design bug- screen menu

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#593]
The screen menu include "back to world view", momentarily linkage, hide layers and add to favorites. in the future- also permanent linkage. it also include the overlay title and designated notifications (not part of the case and without Geo registration) 

Please see-
Active screen-
![image](https://user-images.githubusercontent.com/26301386/30323139-b910bbd0-97c4-11e7-8dbf-6bebb715b9a5.png)

Inactive screen-
![image](https://user-images.githubusercontent.com/26301386/30320616-d4a36b4e-97bb-11e7-8f24-b9d9c4930716.png)

Selected and/or hovered
![image](https://user-images.githubusercontent.com/26301386/30320259-cffd914c-97ba-11e7-80a9-d7a6a5b84055.png)

Disabled-
![image](https://user-images.githubusercontent.com/26301386/30320689-156f1254-97bc-11e7-97a8-e8cb7be727aa.png)

When the screen is not active the icon opacity will be 70% (#FFFFFF), no background, except the "back to W.V". 
When the screen is active-
Normal= icon opacity 100% (#FFFFFF), no background, except the "back to W.V". .  
Hover= icon opacity 100% (#FFFFFF), background #000000, 87% .
Selected= icon opacity 100% (#FFFFFF) [favorite also get a stroke (1px, #E6ECA0, 100%)] , background #000000, 87% .
Disabled= icon opacity 30% (#FFFFFF), no background, except the "back to W.V".

**Comment by carmelorr** [comment]
Icons attached- 
[Colombus - draft.zip](https://github.com/AnSyn/ansyn/files/1295730/Colombus.-.draft.zip)

**Comment by AmitMY** [comment]
Waiting for new icons to finish up the favorites

**Comment by asafMasa** [comment]
@carmelorr @idanbarak what about those icons?

**Comment by AmitMY** [comment]
@asafMasa I think there is a misunderstanding
I have the icons, but I am waiting for a flag from Ohad, so we will be on the same page. (hide layers on map)

**Comment by asafMasa** [comment]
ok

**Comment by asafMasa** [comment]
waiting for #538 to finish
