### ISSUE TITLE
Cosmetic bug- time picker

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#603]
Can't see the whole letters in the month name. For example- May, June, etc.

![image](https://user-images.githubusercontent.com/26301386/30363538-4b31abce-9869-11e7-99b8-56eb010ca9d9.png)
![image](https://user-images.githubusercontent.com/26301386/30363549-5a58a2ec-9869-11e7-8b96-c08b5c3f4d1b.png)

**Comment by osadan** [comment]
this will be in the next release (
