### ISSUE TITLE
Bug - "This overlay is not part of the case" wrong notification 

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#606]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
The label is not disappear after selecting new overlay from the timeline.  

**Expected behavior** 
"This overlay is not part of the case" label should disappear after selecting new overlay to present.

**Minimal reproduction of the problem with instructions** 
1. Launch the application
2. Select overlay from the timeline
![image](https://user-images.githubusercontent.com/6008062/30373744-0317ff60-988b-11e7-8888-9f95b1d276bb.png)

3. Go to filters and select show only the opposite from the selected overlay.
![image](https://user-images.githubusercontent.com/6008062/30373760-12a28234-988b-11e7-9d9d-f9bd3f6f048c.png)

4.  "This overlay is not part of the case" will be shown.
5. Select other overlay from the time line.
![image](https://user-images.githubusercontent.com/6008062/30373785-2a4106fe-988b-11e7-86d2-efbe5a186aff.png)

6. The label "This overlay is not part of the case" still exists.

**Comment by osadan** [comment]
this is will be resolved in #601
