### ISSUE TITLE
Login with generated URL 

### ISSUE THREAD

**Issue by yairtawil** [AnSyn/ansyn#607]
**I'm submitting a ...**  (check one with "x")

```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 

Can't login when `returenUrl` queryParams include generated url
**Expected behavior** 

login success and navigate to `returenUrl`

**solution:**
https://github.com/AnSyn/ansyn/blob/master/src/app/packages/login/login/login.component.ts#L41

change `router.navigate` to `router.navigateByUrl`

**Comment by osadan** [comment]
done
