### ISSUE TITLE
Bug- Go to tool

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#610]
Please change Lat/Long in the WGS 84 line in the "Go to tool"

**Current behavior** 
Geo WGS84 coordinates are wrong, US coordinates go to Antarctica.  Please change LAT/ LONG

**Expected behavior** 
Go to right coordinates (according to google maps)

**Comment by osadan** [comment]
maybe google maps are wrong and we are right ?

**Comment by osadan** [comment]
I think the best is to write lat lon near the boxes

**Comment by osadan** [comment]
@idanbarak check this

**Comment by idanbarak** [comment]
following @osadan recommendation, we have decided to include material design style labels  to each input field (see example at: https://material.angular.io/components/input/overview)

format:
 wgs84 - lat, long,       utm - x, y, zone

**Comment by osadan** [comment]
also adding icon ( that will be changed sometimes in the future ) 
to copy the data to the clipboard
