### ISSUE TITLE
launch "area analysis" context - geo-point input does not affect the case

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#619]
Expected behavior:
launch application and load overlays according to the coordinates specified in the url

Current  behavior:
the same overlay in new jersey is loaded over and over again 

Minimal reproduction of the problem with instructions:
1. Lunch the application with the following Url:
http://ansyn.io/#/login?returnUrl=%2F%3Fcontext%3DArea%2520Analysis%26geopoint%3D-74.07608662469286,40.71400637493053
2. Open new tab and launch the application with the following url:
http://ansyn.io/#/login?returnUrl=%2F%3Fcontext%3DArea%2520Analysis%26geopoint%3D25.07608662469286,30.71400637493053
3. Compare the two presented overlay on the two tabs, you will see that are the same

**Comment by eldadcohen1** [comment]
@idanbarak Please add "Minimal reproduction of the problem with instructions"

**Comment by yairtawil** [comment]
resolved by #621
