### ISSUE TITLE
As a <user>, I want to <create new case according to selected context> so that <the default values that defined in context will affect on the case state>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#63]
After this user story we will have the following:
- [x] Select context when we create new case. (#92)
- [x] All the layout of the app will be changed according to the selected context.(#94)

**Note:** For this iteration we will focus just on the following filters: 

1. TimeType: Absolute - **will be more types and other filters for each time type**
    - From: To:
2. Facets
    - SensorName
    - SensorType: SAR , VIS, IR, Satellite
    - Stereo
    - Resolution
3. Region: GeoJson Polygon

**Comment by MarkShleifer** [comment]
Still need to change from to @osadan #72
