### ISSUE TITLE
refactor(event-drops): create distribution files

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#639]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
[x] Task/UserStory
```

**Current behavior** 
We are using Ohad's custom event drops, straight from a commit, and they don't have distribution files.

**Expected behavior** 
Either we use the normal event drops (preferred), or we publish a package to npm like `event-drops-ansyn` with the distribution script (and `package.json` 'files' field)

**Minimal reproduction of the problem with instructions** 
On the `chrome-44` branch, run `npm run build:prod`

**What is the motivation / use case for changing the behavior?** 
We need the app to compile to es5.
We can either write our own webpack configuration and maintain it, or we can use the @angular/cli configurations.
`@angular/cli` has fixed the [issues we had with the latest version](https://github.com/angular/angular-cli/issues/7741), so we now really just need to fix our packaging to comply with es5.

**Description:**
Ohad, please create a package for our custom event drops OR lets use the official one.

**Comment by osadan** [comment]
there is a script the makes the distribution files

**Comment by AmitMY** [comment]
I know.. Either publish it as a package or lets use the official package, but we can't continue using it from git

**Comment by osadan** [comment]
think. If we where able to take if from the official, why we didn't ?

**Comment by osadan** [comment]
done
