### ISSUE TITLE
design(loader): requires a font icon or an svg

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#645]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Task/UserStory
```

**Current behavior** 
Chrome 44 does not know how to show Emoji correctly
![image](https://user-images.githubusercontent.com/5757359/30806087-ff5ce8b0-a1fc-11e7-928d-3ac0c649e52b.png)

**Expected behavior** 
Loader to look awesome

**Minimal reproduction of the problem with instructions** 
- Open Chrome 44
- Open ansyn.io

**Comment by idanbarak** [comment]
@eldadcohen1 @AmitMY
