### ISSUE TITLE
support(chrome-44): add support to chrome 44

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#648]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
Nothing works in Chrome 44

**Expected behavior** 
Everything should work in Chrome 44

**Minimal reproduction of the problem with instructions** 
- Open Chrome 44
- Go to ansyn.io

**What is the motivation / use case for changing the behavior?** 
Support is good

**Comment by asafMasa** [comment]
@idanbarak @carmelorr need to test with chrome 44
