### ISSUE TITLE
As a <User>, I want <open case that I worked on and it state will affects the app layout> so that <I can continue analyzed the area that I worked on>

### ISSUE THREAD

**Issue by eldadcohen1** [AnSyn/ansyn#65]
After this user story we will have the following:

- [x] The current state of the case will be saved to the mock serve.
      - TimeLine: date range, zoom.
      - Layer tree: selected layers.
      - Imagery View: Zoom level, geographical region
- [x] Case will be open on it last state and it will affect on the application layout.

**Comment by MarkShleifer** [comment]
- Layer tree: selected layers. ToDo
