### ISSUE TITLE
Design Bug: default case anoying filters behaviour 

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#652]
**The Problem**
1. app is loaded with one year range back and build filters (all **checked**)
2. we increase the time range to include more years
3. as a result more data arrives but it's filter check state is **unchecked**

**Proposed solution**
Newly added items types should be **checked** at filtered data sections unless previuosly filtered out

**Comment by idanbarak** [comment]
I Agree with the proposed solution
