### ISSUE TITLE
"Display overlays" appears Disabled  - change to active when overlays are avaliable

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#659]
Current:
1. overlays available in case
2. "Display overlays" appears in disabled mode

Expected:
1. overlays available in case
2. "Display overlays"  appears in normal/static mode

Reproduction:
1. open the app

**Comment by eldadcohen1** [comment]
@idanbarak 
Can you add please print screens.

**Comment by idanbarak** [comment]
@eldadcohen1 yes
