### ISSUE TITLE
Sensor name and sensor type mix up

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#676]
8 band, panchromatic, etc.. - are all sensor types
Geoeye, worldview, etc.. are al sensor names

- [ ] change categories in filters menu
- [ ] Imagery window header should indicate the sensor name (currently indicating type)

**Comment by eldadcohen1** [comment]
@AmitMY 
You should make the change in the overlay source provider.
Switch between sensor name and sensor type.
Please see also if there is something to fix in the default case config also.
