### ISSUE TITLE
base map disappears at certain zoom levels

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#677]
see attached image

when zooming in too much the base map disappears. 
i think we need to block zoom level in order to prevent this

**Comment by idanbarak** [comment]
![screen shot 2017-10-01 at 9 16 53](https://user-images.githubusercontent.com/4181572/31052304-9dd1b74c-a689-11e7-8b18-7453c947647d.png)

**Comment by AmitMY** [comment]
Fixed. Bing map is capped to zoom 19, while you can still zoom in to a pixelated image
