### ISSUE TITLE
filters menu - when collapsing a category "filtered indication" always appears

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#681]
expected: 
1. open filters menu
2. collapse category using the chevron button
3. category collapses - no indication appears

current:
1. open filters menu
2. collapse category using the chevron button
3. category collapses - a "filtered" indication appears

**Comment by eldadcohen1** [comment]
@idanbarak Please add screenshots inline the explanations.

**Comment by idanbarak** [comment]
![screen shot 2017-10-02 at 8 55 04](https://user-images.githubusercontent.com/4181572/31065611-6abdc960-a74f-11e7-91a6-99c597c470ce.png)
![screen shot 2017-10-02 at 8 55 08](https://user-images.githubusercontent.com/4181572/31065612-6abeda76-a74f-11e7-8730-8ca0d4dcd574.png)
