### ISSUE TITLE
feat(map): every map source should supply it's maxZoom

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#682]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
Different maps have different zoom cutoff levels

**Expected behavior** 
You should be abled to specify the zoom level in the provider for that map

**Comment by asafMasa** [comment]
this issue relates #783

**Comment by AmitMY** [comment]
I was asked not to ever limit the max zoom level, but instead limit the max zoom level layer.
I did that for example [here](https://github.com/AnSyn/ansyn/blob/175d9bc7741893af23f8ecdb5b80de11d77715e4/src/app/app/app-providers/map-source-providers/open-layers-BING-source-provider.ts#L20)

@asafMasa this can be closed
