### ISSUE TITLE
Pin point buffer is too big

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#686]
Some overlays that are included in the case do not cover geo filter that was defined by user.

see attached image

**Comment by idanbarak** [comment]
![screen shot 2017-10-01 at 16 03 25](https://user-images.githubusercontent.com/4181572/31054763-a7de6a26-a6c2-11e7-92d3-fa31150d2f22.png)

**Comment by idanbarak** [comment]
minimal reproduction:
http://ansyn.io/#/?facets=(filters:!((fieldName:sensorType,metadata:!(GEOEYE01,WORLDVIEW02,WORLDVIEW01,WORLDVIEW03_VNIR)),(fieldName:sensorName,metadata:!(Panchromatic,'4-band (Blue, Green, Red, NIR) Multispectral','8-band (Coastal, Blue, Green, Yellow, Red, Red-edge, NIR1, NIR2) Multispectral'))),showOnlyFavorites:!f)&time=(from:'2016-10-01T13:01:56.435Z',to:'2017-10-01T13:01:56.435Z',type:absolute)&maps=(active_map_id:default_imagery1,data:!((data:(overlayDisplayMode:Polygon,position:(boundingBox:!((coordinates:!(50.81853037130245,24.776274169706213,0),type:Point),(coordinates:!(50.85882471917506,24.735662139342722,0),type:Point)),center:(coordinates:!(50.83867754523875,24.755969813815838),type:Point),rotation:6.287545840111019,zoom:15.162756967314515)),id:default_imagery1,mapType:openLayersMap),(data:(position:(boundingBox:!((coordinates:!(50.835328373375326,24.763407924379365,0),type:Point),(coordinates:!(50.8685736880862,24.72989799010628,0),type:Point)),center:(coordinates:!(50.85195103073076,24.746654086452764),type:Point),rotation:6.287545840111019,zoom:15.440183417263354)),id:'2357502d-e23c-4c7b-2822-682a3e107073',mapType:openLayersMap)),layouts_index:1)&region=POLYGON ((50.84607108297181 24.744035626014842, 50.84805095303381 24.744035626014842, 50.84805095303381 24.745833704769375, 50.84607108297181 24.745833704769375, 50.84607108297181 24.744035626014842))

**Comment by eldadcohen1** [comment]
@idanbarak What should be the size in m^2 of the buffer?

**Comment by idanbarak** [comment]
0.1 m

**Comment by AmitMY** [comment]
Unfortunetly, Idaho does not respect small polygons, I tried sending 0.1m^2 sized polygons, or even 0m^2, but it seems like Idaho itself has some kind of buffer, that is out of my control..
Their documentation is not explaining this as well, so I'm kind of stuck.
Using a point: https://github.com/AnSyn/ansyn/blob/master/src/app/packages/core/utils/geo.ts#L8
Using a circle with a very small radius: https://github.com/AnSyn/ansyn/blob/master/src/app/packages/core/utils/geo.ts#L12

What should I do about this then?

**Comment by eldadcohen1** [comment]
@AmitMY Create circle with 1m radius.
Find it bounding box and do the query to idaho with this bounding box.
Please put the radius parameter in the config file.

**Comment by asafMasa** [comment]
@AmitMY what is this issue status?

**Comment by AmitMY** [comment]
I am not sure where exactly to put the config parameter for this, as it is needed both in the `menu-items` package and in `map.app.effects`..

I was hoping someone will be here today so I can ask.. I'll finish this tomorrow.
