### ISSUE TITLE
create actions tree

### ISSUE THREAD

**Issue by osadan** [AnSyn/ansyn#689]
Create an actions tree for our application . 
- [ ] Go over all of our effects and add documentation 
- [ ] Create external script that can create a visualize tree of the actions dependency 

```
/**
 @action-from [ACTION_NAME]
 @action-to [ACTION_NAME]
"?" suffix in the end of an action will mark it as optional 
*/
```

**Comment by AmitMY** [comment]
```
npm i -g redux-viewer
rv -s src/
```

**Comment by osadan** [comment]
👏 🥇
