### ISSUE TITLE
Go-to Tool Validation

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#692]
1. Add UTM Ed50 validation 
2. When coordinate is invalid secondary (converted) coordinate system should indicate "invalid" (see attached image for current behavior)

**Comment by eldadcohen1** [comment]
@idanbarak @yairtawil 
I think we need the exact definition for the correct values or we can find something that do the validation for each epsg (Datum)

**Comment by idanbarak** [comment]
@eldadcohen1 @yairtawil 
at the moment i see it as your task to find a validation method that would not require us to manually define validation to each coordinate system. if you will not find a solution i will manually define validation fot UTM ED50

**Comment by eldadcohen1** [comment]
@yairtawil Please make a research for relevant solution that are not based on proj4

**Comment by carmelorr** [comment]
@idanbarak @asafMasa 
did you find/ define the validation method?
The invalid notification is attached to #350

**Comment by idanbarak** [comment]
@carmelorr 
I didnt look for one, yair was suppose to do it, please spend some time and try to solve this. thanks

**Comment by carmelorr** [comment]
As mentioned above, please add an invalid notification:

image

**Comment by yuvalbl** [comment]
Message added. note that it is missing on our (dev) wireframe
