### ISSUE TITLE
Share URL - after rotating an overlay, zoom level (map extent) is wrong 

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#704]
Current:
1. open an overlay and zoom in and rotate (tab 1)
2. share url (tab 1)
3. open url in new tab (tab2)
4. rotation angle is identical to tab 1 , zoom level is **different** to tab 1 

Expected:
1. open an overlay and zoom in and rotate (tab 1)
2. share url (tab 1)
3. open url in new tab (tab2)
4. rotation angle is identical to tab 1 , zoom level is **identical** to tab 1 

Reproduction:
1. open state: https://goo.gl/zNJwC3
2. press share url button
3. open url in new tab - all is good!
4. now back to https://goo.gl/zNJwC3
5. rotate overlay
6. press share url button
7. open url in new tab - **zoom level is different!**

**Comment by yairtawil** [comment]
Same bug:
#729

**Comment by AmitMY** [comment]
Resolved by #761
