### ISSUE TITLE
task(fonts): missing icons, duplicated icons, etc

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#711]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Task/UserStory
```

**Description:**
The `iconmoon` font is lacking.
Several issues:
- icon names are inconsistant. for the same component (tools), we have for example `icon-tools-overlays` and `icon-tools--heatmap`. Use a single dash
- some icons have appended '2' at the end, or have multiple icons but different names, like `icon-filters2` and `icon-main--filters2`
- The following list of icons ship as multiple paths, instead of a single icon
	- icon-status-bar--orientation
	- icon-status-bar--prev
	- icon-status-bar--favorite
	- icon-status-bar--next
	- icon-compass (8! paths)
	- icon-tools--heatmap
	- icon-entity-map-marker
	- icon-permanent-link
- Some svgs are not in the icons pack:
        - /assets/icons/tools/polygons.svg
        - /assets/icons/status-bar/alert.svg
        - /assets/icons/sync_icon.svg
        - /assets/icons/status-bar/screen/[1-6].svg (they are, but it is preferable to have their names 1-6)
        - /assets/eye.svg
        - /assets/icons/status-bar/no-of-screen-icon.svg
        - /assets/icons/status-bar/imagery-count-icon.svg
        - /assets/icons/status-bar/expand-icon.svg

**Comment by carmelorr** [comment]
@AmitMY please see attached
[AnSyn (3).zip](https://github.com/AnSyn/ansyn/files/1385508/AnSyn.3.zip)

**Comment by AmitMY** [comment]
@carmelorr This is much better,

New issues:
`icon-Main`, `icon-Compass`, `icon-Tools`, `icon-Delete`, `icon-Edit`, `icon-Share` should be lowercase

Multiple paths: (much improved, still 4 left)
- icon-Compass (I couldn't find any usage for it, if we don't need it, remove)
- icon-status-bar-imagery-count
- icon-tools-heatmap
- icon-entity-map-marker (I couldn't find any usage for it, if we don't need it, remove)

Missing icons:
`assets/eye.svg`

Other than the current uppercases, please keep the current naming.

**Comment by carmelorr** [comment]
@AmitMY 

Please see- 
[AnSyn (6).zip](https://github.com/AnSyn/ansyn/files/1387738/AnSyn.6.zip)

New issues: done.

Multiple path: 
* Icon-Compass,  icon-tools-heatmap and icon-entity-map-marker - I don't know how to fix them. @AmitMY @idanbarak do you have an idea?
 * icon-status-bar-imagery-count - should be fine now

Missing: it is under different name, please see icon-status-bar-show-pin-point

**Comment by AmitMY** [comment]
@carmelorr thanks
The eye icon is called:
`icon-icon-status-bar-show-pin-point`
can you remove one `icon` from it?

The imagery count is fine now, so just 2 more icons that are messed up, and the compass which I don't see we are using

**Comment by carmelorr** [comment]
@AmitMY  All icons should be fine now, please see-

[AnSyn (7).zip](https://github.com/AnSyn/ansyn/files/1391320/AnSyn.7.zip)

**Comment by carmelorr** [comment]
@AmitMY 
[AnSyn.zip](https://github.com/AnSyn/ansyn/files/1394020/AnSyn.zip)
