### ISSUE TITLE
Add progress bar to overlay load process

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#727]

**Comment by carmelorr** [comment]
@idanbarak is it the same as #580?
https://material.angularjs.org/latest/demo/progressLinear

**Comment by idanbarak** [comment]
@carmelorr 
i think a circular one will be better:
https://material.angularjs.org/latest/demo/progressCircular

**Comment by carmelorr** [comment]
@idanbarak i agree 👍

**Comment by AmitMY** [comment]
Quoting @eldadcohen1 on #580:

> This is already implemented in different way for the time line.

> For the imagery it is implemented inside.

So if I understand this correctly, this issue is about the imagery, and is already done on a fork, so let's just use the code from that fork?

@idanbarak @asafMasa
