### ISSUE TITLE
Failure in presenting overlays - reproduction

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#728]
reproduction:
https://goo.gl/VSqEu1

**Comment by idanbarak** [comment]
![screen shot 2017-10-08 at 15 11 32](https://user-images.githubusercontent.com/4181572/31316684-1d7a8df0-ac3b-11e7-8782-704018fd46bf.png)

**Comment by idanbarak** [comment]
![screen shot 2017-10-08 at 15 11 32](https://user-images.githubusercontent.com/4181572/31316691-36123aca-ac3b-11e7-8ebd-f591a08fe0d7.png)

**Comment by idanbarak** [comment]
see #231

**Comment by asafMasa** [comment]
Duplicate same as #231
