### ISSUE TITLE
display overlays -  z-order - active should always be on top!

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#736]
see Reproduction:
https://goo.gl/K1z6dh

active overlay is hidden by a normal overlay

**Comment by AmitMY** [comment]
Do you mean that you want the active overlay to be infront of the tools overlays wireframes?
![image](https://user-images.githubusercontent.com/5757359/31371096-d6c15a8e-ad97-11e7-936e-105c0b8c0a3a.png)

If that is the case, does the same logic follows for the heatmap?
