### ISSUE TITLE
Bug- share case (duplicate)

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#752]
This bug appeared in both of the share options- by the "share link" and by the  "cases menu".

**Current behavior** 
The case name did not appear on the status bar, in the shared cases (after pasting the url).  instead- "default case" appeared.  

**Expected behavior** 
Case name should be mentioned on the status bar, so the users will be able to tell in which case they are at.  

**Minimal reproduction of the problem with instructions** 
Create new case
Share this case via the "share link" option
paste url in new tab
see "default case" on the status bar
also- share the new case via the cases menu
paste url in new tab
see "default case" on the status bar

**Comment by yuvalbl** [comment]
duplication of #937
Solved in PR #976
Case name should only appear when sharing via "cases menu".
 "share link" only share case as query params
