### ISSUE TITLE
Share case- favorites (duplicate)

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#754]
**Current behavior** 
Can't see favorites after sharing a case (via share link and via cases menu).

**Expected behavior** 
See the favorite overlays after sharing the case. 

**Minimal reproduction of the problem with instructions** 
open new case
select one or more overlays as favorites
share the case
paste url to new tab
can't see the favorite marks on the timeline
can't select show only favorites in the filters.

**Comment by yuvalbl** [comment]
duplication of #937
Solved in PR #976
Favorites should only appear when sharing via "cases menu".
"share link" only share case as query params

**Comment by carmelorr** [comment]
@yuvalbl @asafMasa I can't see the favorites after "share case".
