### ISSUE TITLE
Bug- favorite overlay footprint 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#763]
**Current behavior** 
When facets are on "show only favorites"- the  active overlay footprint is in different colors (green) then the design (blue). When in hover- active is fine (light blue with yellow glow). 
**Expected behavior** 
Active overlay footprint should be in light blue with a yellow glow (without mixing) 
**Minimal reproduction of the problem with instructions** 
Open few screens (i have 4)
Open overlays in the screens and one base map
Mark overlays as favorites
Open the footprint tool in the base map screen (or overlay screen- both the same)
Select one of the overlay screen (activate) and look at the footprint.
 
![image](https://user-images.githubusercontent.com/26301386/31711114-c9d5ba86-b3ff-11e7-8d7b-2f7545822508.png)

![image](https://user-images.githubusercontent.com/26301386/31711206-1713a6b4-b400-11e7-84d5-d5ea5cdd9bfc.png)

**Comment by AmitMY** [comment]
Was probably fixed when I redid the polyline.. @carmelorr I don't understand the issue, can you try to reproduce?

**Comment by carmelorr** [comment]
@yairtawil 
Please change the yellow glow as we discussed.
