### ISSUE TITLE
refactor(pinpoint): externalize as visualizer

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#767]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[X ] Task/UserStory
```

**Current behavior** 
pinpoint functionality is inside map component

**Expected behavior** 
pinpoint functionality in visualizer

**Comment by carmelorr** [comment]
see bug #880
