### ISSUE TITLE
bug tools menu open after refresh 

### ISSUE THREAD

**Issue by osadan** [AnSyn/ansyn#774]
On saved case , after refresh the page when there is an warning 
```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'false'.
    at viewDebugError (core.es5.js:8434)
```
on tools component. 
need to go over all the child component  and check which one makes the problem .

**Comment by osadan** [comment]
The Angular team announced that this will be solved in angular 5

**Comment by asafMasa** [comment]
fixed by upgrading to angular 5
