### ISSUE TITLE
refactor(status-bar): template & style looks bad

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#778]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Task/UserStory
```

**Current behavior** 
The status bar template and style both look bad

**Expected behavior** 
Clean flex grid with clear structure

**Comment by asafMasa** [comment]
@AmitMY was it fixed during half a day look and feel?
