### ISSUE TITLE
Bug (travis, dev and customer site): can't run build:prod command

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#781]
**Info**
run build:prod
--> installs webpack 
--> installs uglifyjs-webpack-plugin 
--> calls post install 
--> installs node-sass
--> ERROR that cause's the process to crush.

**Comment by asafMasa** [comment]
fixed verdaccio issues now it seems we have aot issues

**Comment by asafMasa** [comment]
@AmitMY please fix aout, prod issues and let me know when you are done

**Comment by AmitMY** [comment]
Remove from `tsconfig.app` and `tsconfig.backwards`

```
"files": [
		"typings.d.ts"
	],
```

I'm going now, so I am not putting this in master this second

**Comment by asafMasa** [comment]
Blocked by angular cli bug
