### ISSUE TITLE
Bug- changing overlays cause zoom level distortion

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#783]
**Current behavior** 
Changing overlays by using the arrows (left and right), changes the zoom level of the overlays. 

**Expected behavior** 
Changing the overlays does not effect the zoom level (stay the same). 

**Minimal reproduction of the problem with instructions** 
open an overlay in a certain location
select a specific area ( building for example), use the pin point Geo filter.
change overlays by using the arrows
see that after a few overlays (about 7) the zoom level is not the same.

**Comment by carmelorr** [comment]
@AmitMY

**Comment by asafMasa** [comment]
@AmitMY Why have you closed this? i don't see related PR
