### ISSUE TITLE
Orientation- image perspective

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#785]
As part of the digger functionality, the system will present all images (overlays) on the same azimut as the user sets. 

The user will be able to select the overlay orientation: 

1. Align north
2. Point of view (the angle in which the user rotates the image)
2. Original (the angle in which the image was taken)

**Comment by carmelorr** [comment]
![9 7 1 1](https://user-images.githubusercontent.com/26301386/32165789-9f805522-bd6c-11e7-8bac-daf84d29a100.png)

**Comment by idanbarak** [comment]
@carmelorr 
change "point of view"  to "user perspective"
change "Original"  to "imagery perspective"

**Comment by carmelorr** [comment]
@idanbarak 
![image](https://user-images.githubusercontent.com/26301386/32438735-461e1e3c-c2f4-11e7-8fc5-14a081c7aa1c.png)

**Comment by carmelorr** [comment]
Align north= overlays should appear facing north (in 0 degrees). 
User perspective= overlays should appear in the same angle as the user rotated the current overlay. 
Imagery perspective= overlays should appear in the angle in which the image was taken (requiters calculations or to retrieve from metadata).

**Comment by idanbarak** [comment]
image perspective bug:

http://ansyn.io:81/#/?facets=(filters:!((fieldName:sensorType,metadata:!(Panchromatic,'8-band (Coastal, Blue, Green, Yellow, Red, Red-edge, NIR1, NIR2) Multispectral','4-band (Blue, Green, Red, NIR) Multispectral')),(fieldName:sensorName,metadata:!(WORLDVIEW02,WORLDVIEW03_VNIR,GEOEYE01,WORLDVIEW01)),(fieldName:sourceType,metadata:!(IDAHO))),showOnlyFavorites:!f)&time=(from:'2017-01-02T08:37:44.084Z',to:'2018-01-02T08:37:44.084Z',type:absolute)&maps=(activeMapId:e093c408-dcaa-a697-c6fa-9935921232d5,data:!((data:(isAutoImageProcessingActive:!f,overlay:(id:'69c1c34e-076f-471c-8ec7-765f2804fc42',sourceType:IDAHO),position:(extent:!(55.36536095428379,25.303406078671344,55.37149859367099,25.308798660136034),projectedState:(center:!(6163585.408462291,2913389.497054818),projection:(code:'EPSG:3857'),resolution:0.4388728231570814,rotation:21.64378795644899,zoom:18.444324944911816))),flags:(),id:defaultImagery1,mapType:openLayersMap,progress:1),(data:(overlay:(id:'90816863-3777-49a7-a79a-975cad79e991',sourceType:IDAHO),position:(extent:!(55.36562047825644,25.303375382290042,55.37157937523375,25.30925363492632),projectedState:(center:!(6163604.349781748,2913415.6197431404),projection:(code:'EPSG:3857'),resolution:0.5440740181617972,rotation:10.330664017097444,zoom:18.13432494491181))),flags:(),id:e093c408-dcaa-a697-c6fa-9935921232d5,mapType:openLayersMap,progress:1),(data:(overlay:(id:'56e2a80b-94eb-492e-a84b-a7590b84de80',sourceType:IDAHO),position:(extent:!(55.36489442924375,25.302949578681577,55.372168409259444,25.30946798894702),projectedState:(center:!(6163596.723562457,2913402.602207292),projection:(code:'EPSG:3857'),resolution:0.6278716193060582,rotation:24.35954240189153,zoom:17.927658278245147))),flags:(),id:a705383a-3580-8fb0-eb51-96547a93041e,mapType:openLayersMap,progress:0.8809523809523809)),layoutsIndex:3)&region=POLYGON ((55.36874394557167 25.306290179484613, 55.368763835041 25.306290179484613, 55.368763835041 25.30630816027216, 55.36874394557167 25.30630816027216, 55.36874394557167 25.306290179484613))

**Comment by asafMasa** [comment]
moved to inProgress because of issue #1039
