### ISSUE TITLE
Create manager source provider for overlay source providers

### ISSUE THREAD

**Issue by yairtawil** [AnSyn/ansyn#788]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 

only one active provider for overlays source

**Expected behavior** 

manager source provider that will manage overlay source providers using a strategy(merge).

**Comment by asafMasa** [comment]
@yairtawil i don't understand this issue, please explain it.

**Comment by asafMasa** [comment]
Duplicate same as #786
