### ISSUE TITLE
As a <User>, I want to <have image enhancement ability's>, so that <I can analyze analyze the overlays better>

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#790]
* [x] @idanbarak @carmelorr define the buttons and icons of (gamma, saturation, brightness, contrast, etc.)
* [ ] Add gamma control
* [x] Add brightness control
* [ ] Add saturation control
* [x] Add contrast control

**Comment by carmelorr** [comment]
Please see image processing #271

**Comment by carmelorr** [comment]
Please see bug- #899
