### ISSUE TITLE
Fix Chrome 44 problems

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#794]
* [x] get the specific version
* [ ] fix all reported issues
* [ ] make sure it was fix on prod env

**Comment by AmitMY** [comment]
@osadan @yairtawil Please write which version is it you want use.
Please also write down the issues you found

**Comment by AmitMY** [comment]
44.0.2403.155

**Comment by carmelorr** [comment]
@AmitMY please see #852
