### ISSUE TITLE
Define north arrow indicator complete functionality

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#795]
prev issue #416

**Comment by carmelorr** [comment]
Please see  #416

**Comment by carmelorr** [comment]
@carmelorr add icon

**Comment by carmelorr** [comment]
@asafMasa 
As discussed earlier, please re-open issue #416 

The current issue will be about the rotation functionality.
1. Current level- the rotation will be by designated buttons.
2. Advanced level- rotation will be by loop.

**Comment by carmelorr** [comment]
@idanbarak what do you think?
![image](https://user-images.githubusercontent.com/26301386/32699249-1de0d858-c7bb-11e7-83ff-381fa6c7d6fd.png)

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/32699307-0310b466-c7bc-11e7-9435-63b4e7e13f40.png)

**Comment by carmelorr** [comment]
As decided yesterday, please add tooltip saying: "Press Shift, Alt and drag for rotation"

**Comment by carmelorr** [comment]
Please see the final icon-
![image](https://user-images.githubusercontent.com/26301386/32841598-6dc8168c-ca23-11e7-81d6-42c68314ea70.png)

**Comment by idanbarak** [comment]
@carmelorr 
please define what happens when pressing arrows, how much degrees does the image turns?

**Comment by carmelorr** [comment]
@idanbarak sorry i was under the impression that only the tool tip is needed for now. The image will turn 3.6 degrees per click, total round (360 degrees) will take 100 clicks, 180 degrees turn will take 50 clicks, 90 degrees turn will take 25 clicks.
The rotation will be according the the arrows (left & right).

**Comment by asafMasa** [comment]
@carmelorr @idanbarak this is issue **is not ready for dev** yet...

**Comment by idanbarak** [comment]
@asafMasa it is ready

@carmelorr 
i think 45 degrees is too much, lets make it 10 degrees. and lets add a long (continuous) click that will enable the user to rapidly manipulate the imagery angle.

**Comment by AmitMY** [comment]
@idanbarak I would like to make sure that the drag functionality will not be required in the future.
If it will be, we should just do the compass with an halo now, gradable.

Also, what is the indication for true north vs overlay north?

**Comment by carmelorr** [comment]
"Overlay north"- the overlay will be presented according to the angle in which it was taken. the compass will still point to the real north.

**Comment by carmelorr** [comment]
@AmitMY  as discussed- 
the functionality should be similar to that of google earth- dragging the "N" and pressing a location across the axis. 
Also, please add the tool tip (from compass through axis) saying "Press and drag to turn" 
In addition to the compass tool tip saying "press once to face north, press twice for imagery angle"

**Comment by AmitMY** [comment]
@carmelorr And the arrows? iirc, you said both the dragging and the arrows.

**Comment by asafMasa** [comment]
@carmelorr @idanbarak @AmitMY i think it's closed, am i wrong?

**Comment by asafMasa** [comment]
Arrows are'nt needed
