### ISSUE TITLE
Area Analysis context - the app is loaded with all filters unchecked

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#808]
Expected:
1. load app via url (area analysis context)
2. app is loaded with last 30 overlays of the coordinate input

Current:
1. load app via url (area analysis context)
2. app is loaded no overlays available due to an unwanted filters that are active in the filters menu.

Reproduction:
http://ansyn.io/#/?context=Area%20Analysis&geopoint=53.43084,-2.96075

**Comment by AmitMY** [comment]
@yairtawil @MarkShleifer The context option does not work anymore, any particular reason?

**Comment by MarkShleifer** [comment]
Do you have the last version of the backend?

**Comment by carmelorr** [comment]
@AmitMY please see #310

Imagery count should be 30
Time filter= type-start/end. 
Facets= sensor type- only VIS; resolution- 50 cm1 px; TBD..

Also, @asafMasa please change the parameters for the mapmip launch  accordingly (:81)

**Comment by AmitMY** [comment]
> Imagery count should be 30

I'm looking at the IDAHO request, we are requesting 30, but not getting 30.. @yairtawil / @asafMasa 
> Time filter= type-start/end.

I see start-end
> Facets= sensor type- only VIS; resolution- 50 cm1 px; TBD..

If this is TBD, shouldn't this be "Ready for: Design"? If not, what is VIS?

**Comment by AmitMY** [comment]
Added the missing filters. Because IDAHO is kinda dumb, we can not get a consistent amount of overlays.
Need to check other sources..
