### ISSUE TITLE
Remove overlay from case

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#812]

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/32700088-9f750b48-c7c8-11e7-924a-8a0a09584769.png)

Add indication to the overlays that are not part of the case (status bar?)

**Comment by idanbarak** [comment]
@carmelorr please add the button location to the wireframes

**Comment by carmelorr** [comment]
@idanbarak its the file icon on the imagery menu
![10 6](https://user-images.githubusercontent.com/26301386/33802860-45615e54-dd8a-11e7-980d-786bea82416c.png)

**Comment by idanbarak** [comment]
OK

**Comment by yuvalbl** [comment]
@idanbarak @carmelorr 
please specify behavor for the following scenarios:

1. user load an overlay and click "remove overlay" (what should be displayed at the imagery?)
2. user load overlay, share the case and then click "remove overlay".
(what should be displayed at the imagery, when the shared case is loaded?)

**Comment by carmelorr** [comment]
@yuvalbl 
1. The previous overlay should be displayed (saving the previous overlay is a new behavior that @asafMasa is aware of. it is also related to a current critical bug).
2. The current shared case will be with the overlay. after refresh/ loading again it will be without that overlay. it is related to #1216, ("who has the final say about a case?").

@idanbarak do you agree?

**Comment by idanbarak** [comment]
i agree

**Comment by carmelorr** [comment]
The user will be able to restore **all** the removed overlays to the case by the reset button (filters menu)
The reset button will be available by hovering the "show manually filtered overlays" text (the show/hide will apply only the toggle button itself and not the text).
![image](https://user-images.githubusercontent.com/26301386/44075764-a2f65b4e-9fa6-11e8-8efa-f6d084801323.png)

**Comment by carmelorr** [comment]
Also-
Restore overlay to case-
when the "show manually filtered overlays" toggle is on- the user will be able to restore the removed overlays (when they are open) by the "restore overlay to case" button.
please see-
![image](https://user-images.githubusercontent.com/26301386/44076010-52da5a74-9fa7-11e8-9be1-b92324a390e2.png)
