### ISSUE TITLE
bug(anotations): bugs list

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#814]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
1.
```
ERROR TypeError: Cannot read property 'geometryName_' of undefined
```

2. When painting an arrow, you can paint a lot of points.
![image](https://user-images.githubusercontent.com/5757359/32416138-139ead0c-c24d-11e7-9f18-50e3a85b81ad.png)

**Expected behavior** 
1. no error

2. they want an arrow

**Comment by osadan** [comment]
this is supposed to be . 
(worked hard on it)
can be closed

**Comment by AmitMY** [comment]
1. What about the error?
2. Carmel said it is just an arrow, so I don’t know if this is to spec.. maybe I didn’t get her right

**Comment by osadan** [comment]
if Carmel says that makes the spec
