### ISSUE TITLE
half day of look & feel

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#830]

**Comment by carmelorr** [comment]
![image](https://user-images.githubusercontent.com/26301386/32700370-b84458b4-c7cc-11e7-91cb-1aaa31892140.png)
![image](https://user-images.githubusercontent.com/26301386/32700373-c6ffd586-c7cc-11e7-901a-c2e027e2b142.png)

**Comment by carmelorr** [comment]
See also #846

**Comment by carmelorr** [comment]
Also- new overlay loader: when in more then 1 screen the loader looks like the active screen (but not necessary so..)

**Comment by carmelorr** [comment]
See also issue #819 (time line)

**Comment by AmitMY** [comment]
We decided to close this, in favor of all the other issues
