### ISSUE TITLE
Bug- "fail to load overlay" notification

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#834]
**Current behavior** 
After opening the annotations- every time an overlay is **opened** a notification pops saying "fail to load overlay".

**Expected behavior** 
I expect this notification to appear **only** when an overlay is failed to open

**Minimal reproduction of the problem with instructions** 
Open system
Select overlay or stay on the base map
Open the annotations tools menu
Draw annotations (or try to draw)
Open another overlay from the time line
See notification on the lower left corner

**Comment by asafMasa** [comment]
@AmitMY please let me now if this bug is reproduced
