### ISSUE TITLE
Bug- annotations layer

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#835]
**Current behavior** 
Closing the annotations layer does not remove all the annotations from the map

**Expected behavior** 
All annotation are part of the same layer- therefore they all should be removed when the layer is closed. 
**Minimal reproduction of the problem with instructions** 
Open system
Select overlay
Open the annotations tool
Draw annotations
Open another imagery screen
Activate the annotation layer
Select overlay
Deactivate the annotation layer
See annotation remain (with black fill- another bug)

 Please see attached-

![image](https://user-images.githubusercontent.com/26301386/32717306-ce7c0010-c861-11e7-849b-e7b28e182ae5.png)

**Comment by asafMasa** [comment]
@osadan if it take's more then an hour let me now and i will assign someone else
