### ISSUE TITLE
Bug- filter marker

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#837]
**Current behavior** 
The number on the filter's badge (red button) does not match the number of filters. 

**Expected behavior** 
The badge should indicate the number of inactive filters. 

**Minimal reproduction of the problem with instructions** 
Open the system
Open the filters menu
Check off some sensors types and names
See that the badge indicates incorrect numbers.  

Please see attached-
![image](https://user-images.githubusercontent.com/26301386/32718042-7ba53ff2-c864-11e7-8bc5-bba99d5c1072.png)

**Comment by yairtawil** [comment]
Resolution is not  included on badge

**Comment by carmelorr** [comment]
@yairtawil as discussed, its ok the way it is now

**Comment by yairtawil** [comment]
Thanks @carmelorr !

Resolution should be included on the badge (when start/end is not infinity)

![capture](https://user-images.githubusercontent.com/10003115/33525732-5dae2a74-d83e-11e7-8ad9-2df69164020b.PNG)

**Comment by yairtawil** [comment]
resolved by #923
