### ISSUE TITLE
Bug- open existing cases

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#847]
**Current behavior** 
Can't open some of the existing cases (each time different cases) 
Also, cant open one case after another. 
In both- it wont stop loading.. 
**Expected behavior** 
All cases should open, and the user should be able to navigate between different cases. 
**Minimal reproduction of the problem with instructions** 
Start  the system and try going to existing case
Then try another one

Please see-

![image](https://user-images.githubusercontent.com/26301386/32781258-0f85fed0-c94d-11e7-8482-b8a73b601665.png)

**Comment by asafMasa** [comment]
same as #851 
it is agreed that while in development case's definition are prone to be changed.

So we will clear old cases whenever we change the case's json in a way that may cause a bug (need to make sanity check before approving PR's)
