### ISSUE TITLE
Bug- fail to load old cases

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#851]
**Current behavior** 
can't open old cases (from Terradion and backwards)

**Expected behavior** 

user should be able to open all cases
**Minimal reproduction of the problem with instructions** 
open system
select old existing cases

please see
![image](https://user-images.githubusercontent.com/26301386/32825751-bbbd443c-c9ee-11e7-9ef4-7ed25cc98c93.png)
![image](https://user-images.githubusercontent.com/26301386/32825777-d32888de-c9ee-11e7-90ed-a402c7ee4e61.png)

**Comment by asafMasa** [comment]
@idanbarak is this required? it will enter overhead for dev.
 maybe you should define specific cases that you want us to check

**Comment by asafMasa** [comment]
@AmitMY @yuvalbl  @yairtawil @osadan  @eldadcohen1  @idanbarak @carmelorr it is agreed that while in development case's definition are prone to be changed.

So we will clear old cases whenever we change the case's json in a way that may cause a bug (need to make sanity check before approving PR's)
