### ISSUE TITLE
Bug- chrome 44 loading time 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#852]
**Current behavior** 
Chrome 44 loading time is too long (initial loading and all functions)

**Expected behavior** 
Loading time should be  the same as chrome 61
**Minimal reproduction of the problem with instructions**
See initial loading time
See overlay loading time
See layers loading time

**Comment by AmitMY** [comment]
> Loading time should be the same as chrome 61
Will never happen, as we both add polyfill code, and because chrome@latest is faster than chrome@44

The loading issue is happening as a symptom of an angular-cli bug tracked - https://github.com/angular/angular-cli/issues/5618

**Comment by asafMasa** [comment]
@carmelorr @AmitMY i'm closing this issue please check it after #781 will be fixed
