### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#855]
The app should always present the scale measurements.

**Comment by carmelorr** [comment]
Scale will be according to the system settings= meter or miles per pixel 
 
<img width="1920" alt="10 6" src="https://user-images.githubusercontent.com/26301386/32882275-805da318-cabc-11e7-8a68-a71a25118661.png">
![10 7](https://user-images.githubusercontent.com/26301386/32882372-d109b950-cabc-11e7-8fb1-52bc40a96505.png)

**Comment by idanbarak** [comment]
@carmelorr 
i think scale should be represented by a bar and an indication to the actual "real world" size of the bar. as in google maps for example

**Comment by idanbarak** [comment]
![screen shot 2017-11-19 at 14 23 35](https://user-images.githubusercontent.com/4181572/32990623-5f77c98c-cd35-11e7-8304-283bcb0fd855.png)

**Comment by carmelorr** [comment]
<img width="1920" alt="10 6 1" src="https://user-images.githubusercontent.com/26301386/32991227-0af6bcfa-cd40-11e7-9314-181362bf4f2a.png">
![10 7 1](https://user-images.githubusercontent.com/26301386/32991229-118914dc-cd40-11e7-93de-6d281a89bfb5.png)

**Comment by AmitMY** [comment]
Add current mouse coordinates
