### ISSUE TITLE
feat(case): save current active layers in the case

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#857]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
Case does not save the list of active layers

**Expected behavior** 
Case to save and load the list of active layers

**Comment by osadan** [comment]
the layers in thr long run need to be individual .

**Comment by asafMasa** [comment]
@AmitMY first finish all assigned tasks before dealing with this issue (i'm moving it to icebox)

**Comment by AmitMY** [comment]
@osadan can you expand on that?
@asafMasa this is a dependency of something I have assigned, so it won't get done until this is. I created a separate issue for that, as it diverged from the main #593 issue

**Comment by AmitMY** [comment]
Ohad gave a better solution. I am keeping it open until I have it solved.

About saving as part of the case, dup of #145
