### ISSUE TITLE
Bug- failed to load overlays on the time line

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#863]
**Current behavior** 
Overlays are not available on the time line, due they are shown in the filters menu

**Expected behavior** 
Available overlay should appear on the time line
**Minimal reproduction of the problem with instructions** 
Select a pin point location and compare the time line to the filters menu. 

Please see attached

![image](https://user-images.githubusercontent.com/26301386/32885293-c8d19132-cac5-11e7-94f6-58fbd84b19da.png)

**Comment by asafMasa** [comment]
dg loading version every Thursday
