### ISSUE TITLE
perf(manual-image-processing) when user changing image process parameters - exist worker should be stopped

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#874]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Task/UserStory
```

**What is the motivation / use case for changing the behavior?** 
User can change the image process parameters before processing has finished. in this case
The current (and no longer relevant) web worker should stop it's work

**Comment by asafMasa** [comment]
@yuvalbl Please take an hour to investigate this issue and come back with conclusions
