### ISSUE TITLE
Bug- screen menu

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#879]
**Current behavior** 
Icons on the screen menu are too small and align to the top
**Expected behavior** 
Icons should be bigger and align to the middle. 
**Minimal reproduction of the problem with instructions** 
see screen menu

![image](https://user-images.githubusercontent.com/26301386/33070594-32aa5b3a-cec1-11e7-97fd-cc81baf6e774.png)

**Comment by AmitMY** [comment]
Looking at the actual star icon, I can see that the svg's viewbox is bigger than the star itself, so while I am showing all icons in the same size, this one is just a bad svg.. given the original SVG I can try to fix this if you want.

![image](https://user-images.githubusercontent.com/5757359/33239055-b52e58c4-d2a2-11e7-88d9-76be5a72e10a.png)

Centering the icons is done, now just need it approved

**Comment by carmelorr** [comment]
@AmitMY the icon is still too small. i'll send you a new one

**Comment by AmitMY** [comment]
![image](https://user-images.githubusercontent.com/5757359/34383489-2a33b00e-eb1e-11e7-970b-544575ff1391.png)

**Comment by asafMasa** [comment]
@shaharido1 please check with @carmelorr or @idanbarak if this bug is still relevant and fix it, thanks
