### ISSUE TITLE
Bug- "failed to load tiles"

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#881]
**Current behavior**
When zooming in, a notification appears after few seconds saying how many tiles failed to load (while the overlay is still loading)

**Expected behavior**
The notification should appear in case the tiles actually failed to load, not while they are loading. 

**Minimal reproduction of the problem with instructions** 
Open an overlay
Zoom in (to a building for example)

![image](https://user-images.githubusercontent.com/26301386/33072126-df2fef5a-cec6-11e7-96ee-fa3c78760655.png)

**Comment by AmitMY** [comment]
Every time you start loading a tile, it is added to the loader, as it is an open network request.
If that network request fails for some reason, it will show this message.
I can not reproduce this without going offline, or seeing server errors in the network, which are expected to show the toast.
One thing we would like to do in the future is to cancel network requests when going between overlays for example, so some network load will be cleared 

Please test this again
