### ISSUE TITLE
Bug - when manual image process is active, button should be outlined

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#891]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Current behavior** 
when manual image process is active, button not outlined

**Expected behavior** 
when manual image process is active, button should be outlined
(like when auto-image processing is active)

**Minimal reproduction of the problem with instructions** 
1. load overlay
2. click on manual image processing button tools
3. change settings
4. look at the image manual image processing button

**Comment by carmelorr** [comment]
@yuvalbl when the manual process is active, the outline should remain when the menu is closed.

**Comment by carmelorr** [comment]
@asafMasa  @yuvalbl  please see the comment above, the outline should remain (same as for the auto processing)
