### ISSUE TITLE
Saving manual image processing parameters should not be limited (if overlay manual data changed, save it)

### ISSUE THREAD

**Issue by yuvalbl** [AnSyn/ansyn#892]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Task/UserStory
```

**Description:**
When user is using manual processing excessively, 
~~Saving manual image processing parameters should be limited to last 30 overlays~~
**If overlay manual image processing parameters differ from default save them otherwise remove them from collection**

**Comment by yuvalbl** [comment]
In my opinion this issue should get a very low priority, as manual parameters is a tiny objects (at the moment up to 4 parameters)

**Comment by asafMasa** [comment]
The conclusion is that we will save any overlay that it's manual settings were changed from default.
if set to default this overlay will be removed from collection
No config limitation required
