### ISSUE TITLE
Bug- image enhancement ability 

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#899]
**Current behavior** 
After manual image enhancement- the processed overlay is saved (the user can change overlays and return to the processed overlay) .  However- when sharing the case the manual image enhancement does not save and the unprocessed overlay appears. 

**Expected behavior** 
when sharing the case the manual image enhancement should be save 

**Minimal reproduction of the problem with instructions** 
Open overlay
Change parameters on the "image enhancement" 
Share the case
Paste url to new tab

**Comment by yuvalbl** [comment]
duplication of #872
