### ISSUE TITLE
Bug- Remaining annotations bugs taken from #832

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#900]
Remaining bugs taken from #832
**Current behavior** 
1. The color picker (stroke and fill) dose not always work
2. Annotation's layer does not stay active when the case is shared. 

**Expected behavior** 
1. After selecting colors, i expect them to appear on the annotations
2. I expect the layer to remain selected when the case is shared.

**Minimal reproduction of the problem with instructions** 
1. Try to change the fill and stroke colors
2. Share case and see annotations layer in the layer manager

**Comment by asafMasa** [comment]
@AmitMY After dealing with the above bugs please check that all aspects of annotations works withaout bugs (case sharing , clciking on draw and then close the tool-bar, click twice on draw button, etc.)
