### ISSUE TITLE
bug(manual-enhancement): memory leaks, crashes

### ISSUE THREAD

**Issue by AmitMY** [AnSyn/ansyn#906]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ ] Task/UserStory
```

**Behavior** 
- Opening a case with an overlay shown, that has image enhancement, calls:
`do performSharpness with:  {auto: true}` like a hundred times, and throws an error:
  > "ToolsAppEffects.resetManualImageProcessingArguments$" threw an error
- AnSyn generally consumes 500MB of memory, changing `(change)` to `(input)` (to reproduce this faster), and playing a bit with the sliders, get the app to 2.5GB! It is crucial to fix that, and it would be nice to cancel past enhancements if something new is needed.

**Comment by yuvalbl** [comment]
duplication of #874
