### ISSUE TITLE
Improve the time filter definitions notification

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#921]

**Comment by carmelorr** [comment]
![10 8 2](https://user-images.githubusercontent.com/26301386/33543041-19b869ba-d8de-11e7-94aa-fa5187e0e199.png)

**Comment by carmelorr** [comment]
![10 8 4 2](https://user-images.githubusercontent.com/26301386/33614335-c0b4cce8-d9df-11e7-8814-1f2a552d644d.png)

**Comment by idanbarak** [comment]
@carmelorr 
The indication should be more explicit and accurate - not clear enough, what is the problem? what is the solution?

**Comment by idanbarak** [comment]
see #920

**Comment by asafMasa** [comment]
@yuvalbl please close this issue when you finish with #920
