### ISSUE TITLE
Bug- reload and share case with overlays, pops a "not part of the case" notification while loading

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#952]
**Current behavior** 
Reload and share case with overlays, pops a "not part of the case" notification while loading. after the overlay is loaded the notification disappears. 

**Expected behavior** 
No notification at all, unless needed. 

**Minimal reproduction of the problem with instructions** 
Try to share and reload exciting case with overlays.

**Comment by asafMasa** [comment]
@carmelorr @idanbarak it is by design, recommend to close it

**Comment by idanbarak** [comment]
OK
