### ISSUE TITLE
compass definitions

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#960]
@idanbarak what do you think about the not Geo registered compass? it will also have a tool tip saying "This overlay has no Geo registration". 

Active screen compass-
![image](https://user-images.githubusercontent.com/26301386/33872185-7a3066e4-df1e-11e7-8a3b-509b0325965d.png)

Inactive screen compass-
![image](https://user-images.githubusercontent.com/26301386/33840319-36ce348e-de9d-11e7-9697-b5965fbd338f.png)

Active screen not Geo registered compass-
![image](https://user-images.githubusercontent.com/26301386/33840506-cbcdbcee-de9d-11e7-9835-6897be3c36ba.png)
Or
![image](https://user-images.githubusercontent.com/26301386/33872201-8f6b80f2-df1e-11e7-8e65-dcf049e572fb.png)

Inactive screen not Geo registered compass-
![image](https://user-images.githubusercontent.com/26301386/33840514-d3be376c-de9d-11e7-98fd-11b64d794bc9.png)
Or
![image](https://user-images.githubusercontent.com/26301386/33872213-9ff0b5c8-df1e-11e7-99c0-911c96ff23b3.png)

**Comment by idanbarak** [comment]
i like the big question mark

**Comment by carmelorr** [comment]
@AmitMY

**Comment by yuvalbl** [comment]
@idanbarak 
what about the tool tip @carmelorr  mentioned in the original message?

**Comment by carmelorr** [comment]
@yuvalbl I dont think its needed anymore. we have a tool tip saying "press Alt+shift and drag to rotate"
