### ISSUE TITLE
Bug- launch in entity context

### ISSUE THREAD

**Issue by carmelorr** [AnSyn/ansyn#977]
**Current behavior** 
Entity appears on the map without the text (regarding the time)
**Expected behavior** 

A designated text should appear calculating the time between the overlay and the info entity. 

![image](https://user-images.githubusercontent.com/26301386/34195293-64240e1c-e565-11e7-8261-23e8894dd101.png)

**Minimal reproduction of the problem with instructions**
Open mark's url

**Comment by asafMasa** [comment]
@AmitMY it's the text mark igonored...

**Comment by carmelorr** [comment]
@asafMasa please see bug #1038
