### ISSUE TITLE
prepare usable aerial imagery data (Carmel)

### ISSUE THREAD

**Issue by idanbarak** [AnSyn/ansyn#99]

**Comment by eldadcohen1** [comment]
@idanbarak hi,
Please edit this issue content.
If the template is not fit for you please erase it and add you custom content

**Comment by idanbarak** [comment]
@eldadcohen1

**Comment by asafMasa** [comment]
@carmelorr can we close this issue?

**Comment by carmelorr** [comment]
@asafMasa yes
