### ISSUE TITLE
Bug: (customer site) launch the app with "entity" context doesn't work 

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#992]

**Comment by yuvalbl** [comment]
seems like this commit caused the issue:
25de3d0

@yairtawil check you check it out?
you can use the following link to reconstruct on dev environment

localhost:4200/#/?context=Info%20Entity&geometry=POLYGON((40.73223283859315%20-73.99867057800293,40.730720648507656%20-73.99556994438171,40.72954989709701%20-73.99656772613525,40.73106211378899%20-73.99962544441223,40.73223283859315%20-73.99867057800293)))&time=2015-11-11T09:25:40

**Comment by ronenru** [comment]
Issue moved to [AnSyn/PrivIssues #7](https://github.com/AnSyn/PrivIssues/issues/7) via [**ZenHub**](https://www.zenhub.com/)
