### ISSUE TITLE
Get "filtered" overlays from provider

### ISSUE THREAD

**Issue by asafMasa** [AnSyn/ansyn#997]
In order to handle large data requests we can't rely on post-request facets .
We need to have an option to request already filtered data.

**Comment by carmelorr** [comment]
@idanbarak is this for this iteration?

**Comment by idanbarak** [comment]
@carmelorr 
we can design it, but it wont be developed in this iteration

**Comment by idanbarak** [comment]
@carmelorr 
I have started working on this issue

**Comment by idanbarak** [comment]
http://gijgo.com/tree/demos/material-design-treeview-checkbox

**Comment by idanbarak** [comment]
The following feature will enable the user define the sensor types and names that are requested from the providers, opposed to the current situation when the query us based only on time and geo-spatial properties of the overlays.

**Requirements**
1. add a new filter combo box in the status bar - "Data input filter"
2. Pressing the combo box will open a dialog box that will enable the user to select the required sensors.

3. the list will be a "tree node checkbox" component with 3 hierarchy levels (Provider-Sensor type-Sensor name)

4. for some basic component inspiration please see: 
http://gijgo.com/tree/demos/material-design-treeview-checkboxhttps://tina-material-tree.firebaseapp.com/simple-tree
--

5. the list values (nodes) will be based on a configuration file

6. checkbox states: on/off/partial

7. after pressing "save" the request will be send to the providers.

8. Combo box indication - at the moment let keep it simple, 2 options: Full/Partial


![input filters 2](https://user-images.githubusercontent.com/4181572/38197929-3b858934-3693-11e8-850a-5aec34df4d30.png)
![input filters 1](https://user-images.githubusercontent.com/4181572/38197930-3bacfe10-3693-11e8-8362-05ddb27661be.png)
